"""phase7_compliance_operating_system

Revision ID: 1b7369d836d6
Revises: a375b8149d14
Create Date: 2026-10-03 11:18:58.087515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7369d836d6'
down_revision: Union[str, Sequence[str], None] = 'a375b8149d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_review_campaigns',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('reviewed_items', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_review_campaigns_id'), 'access_review_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_access_review_campaigns_organization_id'), 'access_review_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_access_review_campaigns_status'), 'access_review_campaigns', ['status'], unique=False)
    op.create_table('audit_packages',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('package_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('evaluation_period', sa.String(length=100), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('redaction_level', sa.String(length=100), nullable=False),
    sa.Column('total_evidence_items', sa.Integer(), nullable=False),
    sa.Column('total_policies_included', sa.Integer(), nullable=False),
    sa.Column('total_controls_mapped', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_packages_id'), 'audit_packages', ['id'], unique=False)
    op.create_index(op.f('ix_audit_packages_organization_id'), 'audit_packages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_packages_package_number'), 'audit_packages', ['package_number'], unique=False)
    op.create_index(op.f('ix_audit_packages_status'), 'audit_packages', ['status'], unique=False)
    op.create_table('business_continuity_plans',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('recovery_strategy', sa.Text(), nullable=False),
    sa.Column('communication_plan', sa.Text(), nullable=False),
    sa.Column('last_tested_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_continuity_plans_id'), 'business_continuity_plans', ['id'], unique=False)
    op.create_index(op.f('ix_business_continuity_plans_organization_id'), 'business_continuity_plans', ['organization_id'], unique=False)
    op.create_table('business_impact_analyses',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('critical_service_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('impact_assessment', sa.Text(), nullable=False),
    sa.Column('maximum_tolerable_downtime_hours', sa.Integer(), nullable=False),
    sa.Column('target_rto_minutes', sa.Integer(), nullable=False),
    sa.Column('target_rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('observed_rto_minutes', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=False),
    sa.Column('manual_workaround', sa.Text(), nullable=False),
    sa.Column('recovery_priority', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_impact_analyses_id'), 'business_impact_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_business_impact_analyses_organization_id'), 'business_impact_analyses', ['organization_id'], unique=False)
    op.create_table('canonical_controls',
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('default_implementation_type', sa.String(length=50), nullable=False),
    sa.Column('default_frequency', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_controls_category'), 'canonical_controls', ['category'], unique=False)
    op.create_index(op.f('ix_canonical_controls_control_code'), 'canonical_controls', ['control_code'], unique=True)
    op.create_index(op.f('ix_canonical_controls_id'), 'canonical_controls', ['id'], unique=False)
    op.create_table('commercial_contracts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('contract_value', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('sla_target_availability', sa.String(length=50), nullable=True),
    sa.Column('sla_observed_availability', sa.String(length=50), nullable=True),
    sa.Column('sla_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_contracts_id'), 'commercial_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_contracts_organization_id'), 'commercial_contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_contracts_status'), 'commercial_contracts', ['status'], unique=False)
    op.create_table('compliance_service_projects',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lead_consultant', sa.String(length=255), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('milestones_json', sa.JSON(), nullable=False),
    sa.Column('deliverables_json', sa.JSON(), nullable=False),
    sa.Column('estimated_delivery', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_service_projects_id'), 'compliance_service_projects', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_service_projects_organization_id'), 'compliance_service_projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_service_projects_status'), 'compliance_service_projects', ['status'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recurrence_interval', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_tasks_id'), 'compliance_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_organization_id'), 'compliance_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_status'), 'compliance_tasks', ['status'], unique=False)
    op.create_table('control_operating_periods',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('coverage_summary_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_operating_periods_id'), 'control_operating_periods', ['id'], unique=False)
    op.create_index(op.f('ix_control_operating_periods_organization_id'), 'control_operating_periods', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_operating_periods_status'), 'control_operating_periods', ['status'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('capa_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause_analysis', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('effectiveness_review', sa.Text(), nullable=True),
    sa.Column('effectiveness_reviewer', sa.String(length=255), nullable=True),
    sa.Column('effectiveness_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_capa_number'), 'corrective_actions', ['capa_number'], unique=False)
    op.create_index(op.f('ix_corrective_actions_id'), 'corrective_actions', ['id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_organization_id'), 'corrective_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_status'), 'corrective_actions', ['status'], unique=False)
    op.create_table('data_inventory_items',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('personal_data', sa.Boolean(), nullable=False),
    sa.Column('sensitive_classification', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('data_principals', sa.String(length=255), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('storage_region', sa.String(length=100), nullable=False),
    sa.Column('retention_period', sa.String(length=100), nullable=False),
    sa.Column('deletion_method', sa.String(length=255), nullable=False),
    sa.Column('encryption_in_transit', sa.String(length=100), nullable=False),
    sa.Column('encryption_at_rest', sa.String(length=100), nullable=False),
    sa.Column('access_control', sa.String(length=255), nullable=False),
    sa.Column('subprocessor', sa.String(length=255), nullable=True),
    sa.Column('cross_border_transfer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_inventory_items_id'), 'data_inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_data_inventory_items_organization_id'), 'data_inventory_items', ['organization_id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('system', sa.String(length=255), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('deletion_method', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_organization_id'), 'data_retention_policies', ['organization_id'], unique=False)
    op.create_table('external_assurance_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('assurance_type', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('issuer_auditor', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('document_reference', sa.String(length=255), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_visibility', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_assurance_records_id'), 'external_assurance_records', ['id'], unique=False)
    op.create_index(op.f('ix_external_assurance_records_organization_id'), 'external_assurance_records', ['organization_id'], unique=False)
    op.create_table('framework_versions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('retired_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_framework_versions_code'), 'framework_versions', ['code'], unique=True)
    op.create_index(op.f('ix_framework_versions_id'), 'framework_versions', ['id'], unique=False)
    op.create_table('information_assets',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('data_stored', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_assets_id'), 'information_assets', ['id'], unique=False)
    op.create_index(op.f('ix_information_assets_organization_id'), 'information_assets', ['organization_id'], unique=False)
    op.create_table('interested_parties',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('expectations', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interested_parties_id'), 'interested_parties', ['id'], unique=False)
    op.create_index(op.f('ix_interested_parties_organization_id'), 'interested_parties', ['organization_id'], unique=False)
    op.create_table('internal_audits',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('audit_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('lead_auditor', sa.String(length=255), nullable=False),
    sa.Column('audit_team', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary_notes', sa.Text(), nullable=True),
    sa.Column('report_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_audits_audit_code'), 'internal_audits', ['audit_code'], unique=False)
    op.create_index(op.f('ix_internal_audits_id'), 'internal_audits', ['id'], unique=False)
    op.create_index(op.f('ix_internal_audits_organization_id'), 'internal_audits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_internal_audits_status'), 'internal_audits', ['status'], unique=False)
    op.create_table('isms_scopes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('business_units', sa.Text(), nullable=False),
    sa.Column('products', sa.Text(), nullable=False),
    sa.Column('applications', sa.Text(), nullable=False),
    sa.Column('aws_accounts', sa.Text(), nullable=False),
    sa.Column('locations', sa.Text(), nullable=False),
    sa.Column('people_groups', sa.Text(), nullable=False),
    sa.Column('systems', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('excluded_areas', sa.Text(), nullable=True),
    sa.Column('scope_statement', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isms_scopes_id'), 'isms_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_isms_scopes_organization_id'), 'isms_scopes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_isms_scopes_status'), 'isms_scopes', ['status'], unique=False)
    op.create_table('management_reviews',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('review_title', sa.String(length=255), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('period_covered', sa.String(length=100), nullable=False),
    sa.Column('chairperson', sa.String(length=255), nullable=False),
    sa.Column('attendees_json', sa.JSON(), nullable=False),
    sa.Column('security_objectives_summary', sa.Text(), nullable=False),
    sa.Column('audit_results_summary', sa.Text(), nullable=False),
    sa.Column('incident_and_vapt_summary', sa.Text(), nullable=False),
    sa.Column('risk_assessment_summary', sa.Text(), nullable=False),
    sa.Column('supplier_performance_summary', sa.Text(), nullable=False),
    sa.Column('corrective_actions_summary', sa.Text(), nullable=False),
    sa.Column('improvement_decisions', sa.Text(), nullable=False),
    sa.Column('resource_needs', sa.Text(), nullable=False),
    sa.Column('approved_minutes_markdown', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_reviews_id'), 'management_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_management_reviews_organization_id'), 'management_reviews', ['organization_id'], unique=False)
    op.create_table('organization_contexts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('internal_issues', sa.Text(), nullable=False),
    sa.Column('external_issues', sa.Text(), nullable=False),
    sa.Column('regulatory_landscape', sa.Text(), nullable=False),
    sa.Column('market_context', sa.Text(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_contexts_id'), 'organization_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_organization_contexts_organization_id'), 'organization_contexts', ['organization_id'], unique=False)
    op.create_table('policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('is_mandatory_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_organization_id'), 'policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policies_slug'), 'policies', ['slug'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_table('privacy_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('data_principal_name', sa.String(length=255), nullable=False),
    sa.Column('data_principal_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_requests_data_principal_email'), 'privacy_requests', ['data_principal_email'], unique=False)
    op.create_index(op.f('ix_privacy_requests_id'), 'privacy_requests', ['id'], unique=False)
    op.create_index(op.f('ix_privacy_requests_organization_id'), 'privacy_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_privacy_requests_request_number'), 'privacy_requests', ['request_number'], unique=False)
    op.create_index(op.f('ix_privacy_requests_status'), 'privacy_requests', ['status'], unique=False)
    op.create_table('processing_activities',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('systems_involved', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('data_principals', sa.Text(), nullable=False),
    sa.Column('collection_source', sa.String(length=255), nullable=False),
    sa.Column('processing_basis', sa.String(length=100), nullable=False),
    sa.Column('retention_schedule', sa.String(length=100), nullable=False),
    sa.Column('third_party_sharing', sa.Text(), nullable=True),
    sa.Column('subprocessors_involved', sa.Text(), nullable=True),
    sa.Column('security_safeguards', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_activities_id'), 'processing_activities', ['id'], unique=False)
    op.create_index(op.f('ix_processing_activities_organization_id'), 'processing_activities', ['organization_id'], unique=False)
    op.create_table('risks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('risk_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=255), nullable=False),
    sa.Column('threat', sa.String(length=500), nullable=False),
    sa.Column('vulnerability', sa.String(length=500), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('inherent_score', sa.Integer(), nullable=False),
    sa.Column('existing_controls', sa.Text(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=False),
    sa.Column('residual_impact', sa.Integer(), nullable=False),
    sa.Column('residual_score', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('treatment', sa.String(length=50), nullable=False),
    sa.Column('treatment_justification', sa.Text(), nullable=True),
    sa.Column('treatment_approver', sa.String(length=255), nullable=True),
    sa.Column('treatment_expires_at', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_organization_id'), 'risks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risks_risk_id'), 'risks', ['risk_id'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('security_objectives',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_objectives_id'), 'security_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_security_objectives_organization_id'), 'security_objectives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_objectives_status'), 'security_objectives', ['status'], unique=False)
    op.create_table('soa_entries',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('control_title', sa.String(length=255), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('implementation_status', sa.String(length=50), nullable=False),
    sa.Column('control_owner', sa.String(length=255), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soa_entries_control_code'), 'soa_entries', ['control_code'], unique=False)
    op.create_index(op.f('ix_soa_entries_id'), 'soa_entries', ['id'], unique=False)
    op.create_index(op.f('ix_soa_entries_organization_id'), 'soa_entries', ['organization_id'], unique=False)
    op.create_table('training_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('training_module', sa.String(length=255), nullable=False),
    sa.Column('employee_email', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=True),
    sa.Column('certificate_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_employee_email'), 'training_records', ['employee_email'], unique=False)
    op.create_index(op.f('ix_training_records_id'), 'training_records', ['id'], unique=False)
    op.create_index(op.f('ix_training_records_organization_id'), 'training_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_records_status'), 'training_records', ['status'], unique=False)
    op.create_table('vendors',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dpa_status', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('contract_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_assessment_date', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('security_certifications', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_organization_id'), 'vendors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_table('access_review_decisions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['access_review_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_review_decisions_campaign_id'), 'access_review_decisions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_access_review_decisions_id'), 'access_review_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_access_review_decisions_organization_id'), 'access_review_decisions', ['organization_id'], unique=False)
    op.create_table('audit_package_items',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_reference', sa.String(length=255), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['audit_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_package_items_id'), 'audit_package_items', ['id'], unique=False)
    op.create_index(op.f('ix_audit_package_items_organization_id'), 'audit_package_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_package_items_package_id'), 'audit_package_items', ['package_id'], unique=False)
    op.create_table('control_framework_mappings',
    sa.Column('canonical_control_id', sa.String(length=36), nullable=False),
    sa.Column('framework_version_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_code', sa.String(length=100), nullable=False),
    sa.Column('requirement_title', sa.String(length=255), nullable=False),
    sa.Column('mapping_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_control_id'], ['canonical_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_framework_mappings_canonical_control_id'), 'control_framework_mappings', ['canonical_control_id'], unique=False)
    op.create_index(op.f('ix_control_framework_mappings_framework_version_id'), 'control_framework_mappings', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_control_framework_mappings_id'), 'control_framework_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_control_framework_mappings_requirement_code'), 'control_framework_mappings', ['requirement_code'], unique=False)
    op.create_table('control_implementations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('implementation_description', sa.Text(), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=False),
    sa.Column('applicability_reason', sa.Text(), nullable=True),
    sa.Column('implementation_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('maturity', sa.String(length=50), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['canonical_controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_implementations_control_id'), 'control_implementations', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_implementations_id'), 'control_implementations', ['id'], unique=False)
    op.create_index(op.f('ix_control_implementations_organization_id'), 'control_implementations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_implementations_status'), 'control_implementations', ['status'], unique=False)
    op.create_table('internal_audit_findings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('internal_audit_id', sa.String(length=36), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('corrective_action_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['internal_audit_id'], ['internal_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_audit_findings_id'), 'internal_audit_findings', ['id'], unique=False)
    op.create_index(op.f('ix_internal_audit_findings_internal_audit_id'), 'internal_audit_findings', ['internal_audit_id'], unique=False)
    op.create_index(op.f('ix_internal_audit_findings_organization_id'), 'internal_audit_findings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_internal_audit_findings_status'), 'internal_audit_findings', ['status'], unique=False)
    op.create_table('policy_versions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_id'), 'policy_versions', ['id'], unique=False)
    op.create_index(op.f('ix_policy_versions_organization_id'), 'policy_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_status'), 'policy_versions', ['status'], unique=False)
    op.create_table('risk_treatment_actions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('risk_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('linked_control_code', sa.String(length=100), nullable=True),
    sa.Column('linked_task_id', sa.String(length=100), nullable=True),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_treatment_actions_id'), 'risk_treatment_actions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_treatment_actions_organization_id'), 'risk_treatment_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_treatment_actions_risk_id'), 'risk_treatment_actions', ['risk_id'], unique=False)
    op.create_index(op.f('ix_risk_treatment_actions_status'), 'risk_treatment_actions', ['status'], unique=False)
    op.create_table('vendor_assessments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_title', sa.String(length=255), nullable=False),
    sa.Column('assessor', sa.String(length=255), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('privacy_score', sa.Integer(), nullable=False),
    sa.Column('availability_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_assessments_id'), 'vendor_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_assessments_organization_id'), 'vendor_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vendor_assessments_vendor_id'), 'vendor_assessments', ['vendor_id'], unique=False)
    op.create_table('vendor_findings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation_required', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_findings_id'), 'vendor_findings', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_findings_organization_id'), 'vendor_findings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vendor_findings_status'), 'vendor_findings', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_findings_vendor_id'), 'vendor_findings', ['vendor_id'], unique=False)
    op.create_table('control_evidence_mappings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_implementation_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('quality_state', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_implementation_id'], ['control_implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_evidence_mappings_control_implementation_id'), 'control_evidence_mappings', ['control_implementation_id'], unique=False)
    op.create_index(op.f('ix_control_evidence_mappings_evidence_id'), 'control_evidence_mappings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_control_evidence_mappings_id'), 'control_evidence_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_control_evidence_mappings_organization_id'), 'control_evidence_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_evidence_mappings_quality_state'), 'control_evidence_mappings', ['quality_state'], unique=False)
    op.create_table('control_exceptions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_implementation_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=False),
    sa.Column('affected_period', sa.String(length=100), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_implementation_id'], ['control_implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_exceptions_control_implementation_id'), 'control_exceptions', ['control_implementation_id'], unique=False)
    op.create_index(op.f('ix_control_exceptions_id'), 'control_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_control_exceptions_organization_id'), 'control_exceptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_exceptions_status'), 'control_exceptions', ['status'], unique=False)
    op.create_table('control_tests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_implementation_id', sa.String(length=36), nullable=False),
    sa.Column('operating_period_id', sa.String(length=36), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('exceptions_found', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_implementation_id'], ['control_implementations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_period_id'], ['control_operating_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_tests_control_implementation_id'), 'control_tests', ['control_implementation_id'], unique=False)
    op.create_index(op.f('ix_control_tests_id'), 'control_tests', ['id'], unique=False)
    op.create_index(op.f('ix_control_tests_operating_period_id'), 'control_tests', ['operating_period_id'], unique=False)
    op.create_index(op.f('ix_control_tests_organization_id'), 'control_tests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_tests_result'), 'control_tests', ['result'], unique=False)
    op.create_table('policy_acknowledgements',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('employee_email', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgements_employee_email'), 'policy_acknowledgements', ['employee_email'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgements_id'), 'policy_acknowledgements', ['id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgements_organization_id'), 'policy_acknowledgements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgements_policy_version_id'), 'policy_acknowledgements', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgements_status'), 'policy_acknowledgements', ['status'], unique=False)
    op.create_table('policy_approvals',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('approver_email', sa.String(length=255), nullable=False),
    sa.Column('approver_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_approvals_id'), 'policy_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_policy_approvals_organization_id'), 'policy_approvals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policy_approvals_policy_version_id'), 'policy_approvals', ['policy_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_approvals_policy_version_id'), table_name='policy_approvals')
    op.drop_index(op.f('ix_policy_approvals_organization_id'), table_name='policy_approvals')
    op.drop_index(op.f('ix_policy_approvals_id'), table_name='policy_approvals')
    op.drop_table('policy_approvals')
    op.drop_index(op.f('ix_policy_acknowledgements_status'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acknowledgements_policy_version_id'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acknowledgements_organization_id'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acknowledgements_id'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acknowledgements_employee_email'), table_name='policy_acknowledgements')
    op.drop_table('policy_acknowledgements')
    op.drop_index(op.f('ix_control_tests_result'), table_name='control_tests')
    op.drop_index(op.f('ix_control_tests_organization_id'), table_name='control_tests')
    op.drop_index(op.f('ix_control_tests_operating_period_id'), table_name='control_tests')
    op.drop_index(op.f('ix_control_tests_id'), table_name='control_tests')
    op.drop_index(op.f('ix_control_tests_control_implementation_id'), table_name='control_tests')
    op.drop_table('control_tests')
    op.drop_index(op.f('ix_control_exceptions_status'), table_name='control_exceptions')
    op.drop_index(op.f('ix_control_exceptions_organization_id'), table_name='control_exceptions')
    op.drop_index(op.f('ix_control_exceptions_id'), table_name='control_exceptions')
    op.drop_index(op.f('ix_control_exceptions_control_implementation_id'), table_name='control_exceptions')
    op.drop_table('control_exceptions')
    op.drop_index(op.f('ix_control_evidence_mappings_quality_state'), table_name='control_evidence_mappings')
    op.drop_index(op.f('ix_control_evidence_mappings_organization_id'), table_name='control_evidence_mappings')
    op.drop_index(op.f('ix_control_evidence_mappings_id'), table_name='control_evidence_mappings')
    op.drop_index(op.f('ix_control_evidence_mappings_evidence_id'), table_name='control_evidence_mappings')
    op.drop_index(op.f('ix_control_evidence_mappings_control_implementation_id'), table_name='control_evidence_mappings')
    op.drop_table('control_evidence_mappings')
    op.drop_index(op.f('ix_vendor_findings_vendor_id'), table_name='vendor_findings')
    op.drop_index(op.f('ix_vendor_findings_status'), table_name='vendor_findings')
    op.drop_index(op.f('ix_vendor_findings_organization_id'), table_name='vendor_findings')
    op.drop_index(op.f('ix_vendor_findings_id'), table_name='vendor_findings')
    op.drop_table('vendor_findings')
    op.drop_index(op.f('ix_vendor_assessments_vendor_id'), table_name='vendor_assessments')
    op.drop_index(op.f('ix_vendor_assessments_organization_id'), table_name='vendor_assessments')
    op.drop_index(op.f('ix_vendor_assessments_id'), table_name='vendor_assessments')
    op.drop_table('vendor_assessments')
    op.drop_index(op.f('ix_risk_treatment_actions_status'), table_name='risk_treatment_actions')
    op.drop_index(op.f('ix_risk_treatment_actions_risk_id'), table_name='risk_treatment_actions')
    op.drop_index(op.f('ix_risk_treatment_actions_organization_id'), table_name='risk_treatment_actions')
    op.drop_index(op.f('ix_risk_treatment_actions_id'), table_name='risk_treatment_actions')
    op.drop_table('risk_treatment_actions')
    op.drop_index(op.f('ix_policy_versions_status'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_organization_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_internal_audit_findings_status'), table_name='internal_audit_findings')
    op.drop_index(op.f('ix_internal_audit_findings_organization_id'), table_name='internal_audit_findings')
    op.drop_index(op.f('ix_internal_audit_findings_internal_audit_id'), table_name='internal_audit_findings')
    op.drop_index(op.f('ix_internal_audit_findings_id'), table_name='internal_audit_findings')
    op.drop_table('internal_audit_findings')
    op.drop_index(op.f('ix_control_implementations_status'), table_name='control_implementations')
    op.drop_index(op.f('ix_control_implementations_organization_id'), table_name='control_implementations')
    op.drop_index(op.f('ix_control_implementations_id'), table_name='control_implementations')
    op.drop_index(op.f('ix_control_implementations_control_id'), table_name='control_implementations')
    op.drop_table('control_implementations')
    op.drop_index(op.f('ix_control_framework_mappings_requirement_code'), table_name='control_framework_mappings')
    op.drop_index(op.f('ix_control_framework_mappings_id'), table_name='control_framework_mappings')
    op.drop_index(op.f('ix_control_framework_mappings_framework_version_id'), table_name='control_framework_mappings')
    op.drop_index(op.f('ix_control_framework_mappings_canonical_control_id'), table_name='control_framework_mappings')
    op.drop_table('control_framework_mappings')
    op.drop_index(op.f('ix_audit_package_items_package_id'), table_name='audit_package_items')
    op.drop_index(op.f('ix_audit_package_items_organization_id'), table_name='audit_package_items')
    op.drop_index(op.f('ix_audit_package_items_id'), table_name='audit_package_items')
    op.drop_table('audit_package_items')
    op.drop_index(op.f('ix_access_review_decisions_organization_id'), table_name='access_review_decisions')
    op.drop_index(op.f('ix_access_review_decisions_id'), table_name='access_review_decisions')
    op.drop_index(op.f('ix_access_review_decisions_campaign_id'), table_name='access_review_decisions')
    op.drop_table('access_review_decisions')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_organization_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_training_records_status'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_organization_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_employee_email'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_soa_entries_organization_id'), table_name='soa_entries')
    op.drop_index(op.f('ix_soa_entries_id'), table_name='soa_entries')
    op.drop_index(op.f('ix_soa_entries_control_code'), table_name='soa_entries')
    op.drop_table('soa_entries')
    op.drop_index(op.f('ix_security_objectives_status'), table_name='security_objectives')
    op.drop_index(op.f('ix_security_objectives_organization_id'), table_name='security_objectives')
    op.drop_index(op.f('ix_security_objectives_id'), table_name='security_objectives')
    op.drop_table('security_objectives')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_organization_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_processing_activities_organization_id'), table_name='processing_activities')
    op.drop_index(op.f('ix_processing_activities_id'), table_name='processing_activities')
    op.drop_table('processing_activities')
    op.drop_index(op.f('ix_privacy_requests_status'), table_name='privacy_requests')
    op.drop_index(op.f('ix_privacy_requests_request_number'), table_name='privacy_requests')
    op.drop_index(op.f('ix_privacy_requests_organization_id'), table_name='privacy_requests')
    op.drop_index(op.f('ix_privacy_requests_id'), table_name='privacy_requests')
    op.drop_index(op.f('ix_privacy_requests_data_principal_email'), table_name='privacy_requests')
    op.drop_table('privacy_requests')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_slug'), table_name='policies')
    op.drop_index(op.f('ix_policies_organization_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_organization_contexts_organization_id'), table_name='organization_contexts')
    op.drop_index(op.f('ix_organization_contexts_id'), table_name='organization_contexts')
    op.drop_table('organization_contexts')
    op.drop_index(op.f('ix_management_reviews_organization_id'), table_name='management_reviews')
    op.drop_index(op.f('ix_management_reviews_id'), table_name='management_reviews')
    op.drop_table('management_reviews')
    op.drop_index(op.f('ix_isms_scopes_status'), table_name='isms_scopes')
    op.drop_index(op.f('ix_isms_scopes_organization_id'), table_name='isms_scopes')
    op.drop_index(op.f('ix_isms_scopes_id'), table_name='isms_scopes')
    op.drop_table('isms_scopes')
    op.drop_index(op.f('ix_internal_audits_status'), table_name='internal_audits')
    op.drop_index(op.f('ix_internal_audits_organization_id'), table_name='internal_audits')
    op.drop_index(op.f('ix_internal_audits_id'), table_name='internal_audits')
    op.drop_index(op.f('ix_internal_audits_audit_code'), table_name='internal_audits')
    op.drop_table('internal_audits')
    op.drop_index(op.f('ix_interested_parties_organization_id'), table_name='interested_parties')
    op.drop_index(op.f('ix_interested_parties_id'), table_name='interested_parties')
    op.drop_table('interested_parties')
    op.drop_index(op.f('ix_information_assets_organization_id'), table_name='information_assets')
    op.drop_index(op.f('ix_information_assets_id'), table_name='information_assets')
    op.drop_table('information_assets')
    op.drop_index(op.f('ix_framework_versions_id'), table_name='framework_versions')
    op.drop_index(op.f('ix_framework_versions_code'), table_name='framework_versions')
    op.drop_table('framework_versions')
    op.drop_index(op.f('ix_external_assurance_records_organization_id'), table_name='external_assurance_records')
    op.drop_index(op.f('ix_external_assurance_records_id'), table_name='external_assurance_records')
    op.drop_table('external_assurance_records')
    op.drop_index(op.f('ix_data_retention_policies_organization_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_data_inventory_items_organization_id'), table_name='data_inventory_items')
    op.drop_index(op.f('ix_data_inventory_items_id'), table_name='data_inventory_items')
    op.drop_table('data_inventory_items')
    op.drop_index(op.f('ix_corrective_actions_status'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_organization_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_capa_number'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_control_operating_periods_status'), table_name='control_operating_periods')
    op.drop_index(op.f('ix_control_operating_periods_organization_id'), table_name='control_operating_periods')
    op.drop_index(op.f('ix_control_operating_periods_id'), table_name='control_operating_periods')
    op.drop_table('control_operating_periods')
    op.drop_index(op.f('ix_compliance_tasks_status'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_organization_id'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_id'), table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index(op.f('ix_compliance_service_projects_status'), table_name='compliance_service_projects')
    op.drop_index(op.f('ix_compliance_service_projects_organization_id'), table_name='compliance_service_projects')
    op.drop_index(op.f('ix_compliance_service_projects_id'), table_name='compliance_service_projects')
    op.drop_table('compliance_service_projects')
    op.drop_index(op.f('ix_commercial_contracts_status'), table_name='commercial_contracts')
    op.drop_index(op.f('ix_commercial_contracts_organization_id'), table_name='commercial_contracts')
    op.drop_index(op.f('ix_commercial_contracts_id'), table_name='commercial_contracts')
    op.drop_table('commercial_contracts')
    op.drop_index(op.f('ix_canonical_controls_id'), table_name='canonical_controls')
    op.drop_index(op.f('ix_canonical_controls_control_code'), table_name='canonical_controls')
    op.drop_index(op.f('ix_canonical_controls_category'), table_name='canonical_controls')
    op.drop_table('canonical_controls')
    op.drop_index(op.f('ix_business_impact_analyses_organization_id'), table_name='business_impact_analyses')
    op.drop_index(op.f('ix_business_impact_analyses_id'), table_name='business_impact_analyses')
    op.drop_table('business_impact_analyses')
    op.drop_index(op.f('ix_business_continuity_plans_organization_id'), table_name='business_continuity_plans')
    op.drop_index(op.f('ix_business_continuity_plans_id'), table_name='business_continuity_plans')
    op.drop_table('business_continuity_plans')
    op.drop_index(op.f('ix_audit_packages_status'), table_name='audit_packages')
    op.drop_index(op.f('ix_audit_packages_package_number'), table_name='audit_packages')
    op.drop_index(op.f('ix_audit_packages_organization_id'), table_name='audit_packages')
    op.drop_index(op.f('ix_audit_packages_id'), table_name='audit_packages')
    op.drop_table('audit_packages')
    op.drop_index(op.f('ix_access_review_campaigns_status'), table_name='access_review_campaigns')
    op.drop_index(op.f('ix_access_review_campaigns_organization_id'), table_name='access_review_campaigns')
    op.drop_index(op.f('ix_access_review_campaigns_id'), table_name='access_review_campaigns')
    op.drop_table('access_review_campaigns')
    # ### end Alembic commands ###
