"""phase8_commercial_saas_operating_system

Revision ID: 2ee537f7dc1f
Revises: 1b7369d836d6
Create Date: 2026-10-03 16:58:07.134341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.migration_types import enum_type


# revision identifiers, used by Alembic.
revision: str = '2ee537f7dc1f'
down_revision: Union[str, Sequence[str], None] = '1b7369d836d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    if op.get_bind().dialect.name == 'postgresql':
        # Existing membership roles are a PostgreSQL enum, extended in place.
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE membershiprole ADD VALUE IF NOT EXISTS 'BILLING'")
            op.execute("ALTER TYPE membershiprole ADD VALUE IF NOT EXISTS 'CONSULTANT'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_coupons_code'), 'commercial_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_commercial_coupons_id'), 'commercial_coupons', ['id'], unique=False)
    op.create_table('commercial_crm_leads',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', enum_type('NEW', 'CONTACTED', 'QUALIFIED', 'UNQUALIFIED', name='leadstatus'), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_crm_leads_email'), 'commercial_crm_leads', ['email'], unique=False)
    op.create_index(op.f('ix_commercial_crm_leads_id'), 'commercial_crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_crm_leads_status'), 'commercial_crm_leads', ['status'], unique=False)
    op.create_table('commercial_feature_flag_overrides',
    sa.Column('flag_key', sa.String(length=100), nullable=False),
    sa.Column('scope_type', enum_type('GLOBAL', 'PLAN', 'ORGANIZATION', 'USER', name='featureflagscope'), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_feature_flag_overrides_flag_key'), 'commercial_feature_flag_overrides', ['flag_key'], unique=False)
    op.create_index(op.f('ix_commercial_feature_flag_overrides_id'), 'commercial_feature_flag_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_feature_flag_overrides_scope_id'), 'commercial_feature_flag_overrides', ['scope_id'], unique=False)
    op.create_table('commercial_feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_feature_flags_id'), 'commercial_feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_feature_flags_key'), 'commercial_feature_flags', ['key'], unique=True)
    op.create_table('commercial_platform_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_platform_settings_id'), 'commercial_platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_platform_settings_key'), 'commercial_platform_settings', ['key'], unique=True)
    op.create_table('commercial_products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_products_id'), 'commercial_products', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_products_product_code'), 'commercial_products', ['product_code'], unique=True)
    op.create_table('commercial_status_incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', enum_type('INVESTIGATING', 'IDENTIFIED', 'MONITORING', 'RESOLVED', name='statusincidentstate'), nullable=False),
    sa.Column('impact', enum_type('NONE', 'MINOR', 'MAJOR', 'CRITICAL', name='statusincidentimpact'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('affected_components_json', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_status_incidents_id'), 'commercial_status_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_status_incidents_state'), 'commercial_status_incidents', ['state'], unique=False)
    op.create_table('commercial_support_slas',
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('priority', enum_type('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('first_response_hours', sa.Float(), nullable=False),
    sa.Column('resolution_hours', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_support_slas_id'), 'commercial_support_slas', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_support_slas_plan_tier'), 'commercial_support_slas', ['plan_tier'], unique=False)
    op.create_table('commercial_usage_metric_definitions',
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_usage_metric_definitions_id'), 'commercial_usage_metric_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_usage_metric_definitions_metric_key'), 'commercial_usage_metric_definitions', ['metric_key'], unique=True)
    op.create_table('commercial_auditor_evidence_comments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_request_id', sa.String(length=100), nullable=True),
    sa.Column('evidence_id', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('action', enum_type('COMMENT', 'ACCEPT_EVIDENCE', 'REJECT_EVIDENCE', 'REQUEST_CLARIFICATION', name='auditorcommentaction'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_auditor_evidence_comments_evidence_id'), 'commercial_auditor_evidence_comments', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_commercial_auditor_evidence_comments_evidence_request_id'), 'commercial_auditor_evidence_comments', ['evidence_request_id'], unique=False)
    op.create_index(op.f('ix_commercial_auditor_evidence_comments_id'), 'commercial_auditor_evidence_comments', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_auditor_evidence_comments_organization_id'), 'commercial_auditor_evidence_comments', ['organization_id'], unique=False)
    op.create_table('commercial_billing_customers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('default_payment_method_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_billing_customers_id'), 'commercial_billing_customers', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_billing_customers_organization_id'), 'commercial_billing_customers', ['organization_id'], unique=True)
    op.create_index(op.f('ix_commercial_billing_customers_razorpay_customer_id'), 'commercial_billing_customers', ['razorpay_customer_id'], unique=True)
    op.create_index(op.f('ix_commercial_billing_customers_stripe_customer_id'), 'commercial_billing_customers', ['stripe_customer_id'], unique=True)
    op.create_table('commercial_crm_opportunities',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('stage', enum_type('NEW', 'QUALIFIED', 'DISCOVERY', 'SOLUTION_DESIGN', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', name='opportunitystage'), nullable=False),
    sa.Column('product_or_service', sa.String(length=255), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['commercial_crm_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_crm_opportunities_id'), 'commercial_crm_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_crm_opportunities_organization_id'), 'commercial_crm_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_crm_opportunities_stage'), 'commercial_crm_opportunities', ['stage'], unique=False)
    op.create_table('commercial_customer_success_health',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', enum_type('HEALTHY', 'NEEDS_ATTENTION', 'AT_RISK', 'UNKNOWN', name='customerhealthstatus'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_customer_success_health_id'), 'commercial_customer_success_health', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_customer_success_health_organization_id'), 'commercial_customer_success_health', ['organization_id'], unique=True)
    op.create_index(op.f('ix_commercial_customer_success_health_status'), 'commercial_customer_success_health', ['status'], unique=False)
    op.create_table('commercial_customer_success_tasks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_customer_success_tasks_id'), 'commercial_customer_success_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_customer_success_tasks_organization_id'), 'commercial_customer_success_tasks', ['organization_id'], unique=False)
    op.create_table('commercial_email_verification_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_email_verification_tokens_id'), 'commercial_email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_email_verification_tokens_token_hash'), 'commercial_email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_commercial_email_verification_tokens_user_id'), 'commercial_email_verification_tokens', ['user_id'], unique=False)
    op.create_table('commercial_evidence_connectors',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('connector_type', enum_type('GITHUB_ENTERPRISE', 'DATADOG', 'OKTA', 'GOOGLE_WORKSPACE', name='connectortype'), nullable=False),
    sa.Column('status', enum_type('NOT_CONFIGURED', 'CONNECTED', 'DEGRADED', 'ERROR', 'REVOKED', name='connectorstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_evidence_connectors_connector_type'), 'commercial_evidence_connectors', ['connector_type'], unique=False)
    op.create_index(op.f('ix_commercial_evidence_connectors_id'), 'commercial_evidence_connectors', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_evidence_connectors_organization_id'), 'commercial_evidence_connectors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_evidence_connectors_status'), 'commercial_evidence_connectors', ['status'], unique=False)
    op.create_table('commercial_invitations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', enum_type('OWNER', 'ADMIN', 'DEVELOPER', 'DEVOPS', 'SECURITY', 'COMPLIANCE', 'AUDITOR', 'BILLING', 'CONSULTANT', 'VIEWER', name='membershiprole'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', enum_type('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_invitations_email'), 'commercial_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_commercial_invitations_id'), 'commercial_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_invitations_organization_id'), 'commercial_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_invitations_status'), 'commercial_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_commercial_invitations_token_hash'), 'commercial_invitations', ['token_hash'], unique=True)
    op.create_table('commercial_onboarding_states',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed_steps_json', sa.Text(), nullable=False),
    sa.Column('milestones_json', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_onboarding_states_id'), 'commercial_onboarding_states', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_onboarding_states_organization_id'), 'commercial_onboarding_states', ['organization_id'], unique=True)
    op.create_table('commercial_organization_entitlements',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('value_type', enum_type('BOOLEAN', 'NUMERIC', 'STRING', name='valuetype'), nullable=False),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('source', enum_type('PLAN', 'ADDON', 'ENTERPRISE_OVERRIDE', 'TRIAL', 'PROMOTION', 'MANUAL_ADMIN', name='entitlementsource'), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_organization_entitlements_feature_key'), 'commercial_organization_entitlements', ['feature_key'], unique=False)
    op.create_index(op.f('ix_commercial_organization_entitlements_id'), 'commercial_organization_entitlements', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_organization_entitlements_organization_id'), 'commercial_organization_entitlements', ['organization_id'], unique=False)
    op.create_table('commercial_organization_profiles',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('security_email', sa.String(length=255), nullable=True),
    sa.Column('compliance_email', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_organization_profiles_gstin'), 'commercial_organization_profiles', ['gstin'], unique=False)
    op.create_index(op.f('ix_commercial_organization_profiles_id'), 'commercial_organization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_organization_profiles_organization_id'), 'commercial_organization_profiles', ['organization_id'], unique=True)
    op.create_table('commercial_password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_password_reset_tokens_id'), 'commercial_password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_password_reset_tokens_token_hash'), 'commercial_password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_commercial_password_reset_tokens_user_id'), 'commercial_password_reset_tokens', ['user_id'], unique=False)
    op.create_table('commercial_plans',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('tier', enum_type('STARTER', 'GROWTH', 'BUSINESS', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['commercial_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_plans_id'), 'commercial_plans', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_plans_product_id'), 'commercial_plans', ['product_id'], unique=False)
    op.create_index(op.f('ix_commercial_plans_tier'), 'commercial_plans', ['tier'], unique=True)
    op.create_table('commercial_product_events',
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_product_events_event_name'), 'commercial_product_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_commercial_product_events_id'), 'commercial_product_events', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_product_events_organization_id'), 'commercial_product_events', ['organization_id'], unique=False)
    op.create_table('commercial_service_quotes',
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('deliverables_description', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('status', enum_type('DRAFT', 'INTERNAL_REVIEW', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='quotestatus'), nullable=False),
    sa.Column('proposal_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_service_quotes_id'), 'commercial_service_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_service_quotes_organization_id'), 'commercial_service_quotes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_service_quotes_quote_number'), 'commercial_service_quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_commercial_service_quotes_status'), 'commercial_service_quotes', ['status'], unique=False)
    op.create_table('commercial_subscriptions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('status', enum_type('TRIALING', 'ACTIVE', 'PAST_DUE', 'PAYMENT_FAILED', 'GRACE_PERIOD', 'PAUSED', 'CANCEL_AT_PERIOD_END', 'CANCELLED', 'EXPIRED', 'INVOICE_ONLY', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_provider', enum_type('STRIPE', 'RAZORPAY', 'MANUAL_INVOICE', name='billingprovidertype'), nullable=False),
    sa.Column('external_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_subscriptions_external_subscription_id'), 'commercial_subscriptions', ['external_subscription_id'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_id'), 'commercial_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_organization_id'), 'commercial_subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_commercial_subscriptions_status'), 'commercial_subscriptions', ['status'], unique=False)
    op.create_table('commercial_support_tickets',
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', enum_type('BILLING', 'DEPLOYMENT', 'AWS', 'SECURITY', 'VAPT', 'COMPLIANCE', 'BUG', 'ACCOUNT', 'FEATURE_REQUEST', 'INCIDENT', name='ticketcategory'), nullable=False),
    sa.Column('priority', enum_type('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('status', enum_type('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('sla_response_due_at', sa.DateTime(), nullable=True),
    sa.Column('first_responded_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_support_tickets_id'), 'commercial_support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_support_tickets_organization_id'), 'commercial_support_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_support_tickets_status'), 'commercial_support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_commercial_support_tickets_ticket_number'), 'commercial_support_tickets', ['ticket_number'], unique=True)
    op.create_table('commercial_usage_aggregates',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_usage_aggregates_id'), 'commercial_usage_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_usage_aggregates_metric_key'), 'commercial_usage_aggregates', ['metric_key'], unique=False)
    op.create_index(op.f('ix_commercial_usage_aggregates_organization_id'), 'commercial_usage_aggregates', ['organization_id'], unique=False)
    op.create_table('commercial_usage_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=150), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_usage_events_id'), 'commercial_usage_events', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_usage_events_idempotency_key'), 'commercial_usage_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_commercial_usage_events_metric_key'), 'commercial_usage_events', ['metric_key'], unique=False)
    op.create_index(op.f('ix_commercial_usage_events_organization_id'), 'commercial_usage_events', ['organization_id'], unique=False)
    op.create_table('commercial_user_mfa_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=255), nullable=False),
    sa.Column('backup_codes_hash', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_user_mfa_credentials_id'), 'commercial_user_mfa_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_user_mfa_credentials_user_id'), 'commercial_user_mfa_credentials', ['user_id'], unique=True)
    op.create_table('commercial_connector_sync_runs',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['commercial_evidence_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_connector_sync_runs_connector_id'), 'commercial_connector_sync_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_commercial_connector_sync_runs_id'), 'commercial_connector_sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_connector_sync_runs_organization_id'), 'commercial_connector_sync_runs', ['organization_id'], unique=False)
    op.create_table('commercial_invoices',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', enum_type('DRAFT', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID', name='invoicestatus'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tax_breakdown_json', sa.Text(), nullable=True),
    sa.Column('customer_legal_name', sa.String(length=255), nullable=False),
    sa.Column('customer_gstin', sa.String(length=20), nullable=True),
    sa.Column('customer_state', sa.String(length=100), nullable=True),
    sa.Column('billing_provider', enum_type('STRIPE', 'RAZORPAY', 'MANUAL_INVOICE', name='billingprovidertype'), nullable=False),
    sa.Column('external_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('payment_due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_invoices_id'), 'commercial_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_invoices_invoice_number'), 'commercial_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_commercial_invoices_organization_id'), 'commercial_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_invoices_status'), 'commercial_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_commercial_invoices_subscription_id'), 'commercial_invoices', ['subscription_id'], unique=False)
    op.create_table('commercial_plan_entitlements',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('value_type', enum_type('BOOLEAN', 'NUMERIC', 'STRING', name='valuetype'), nullable=False),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['commercial_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_plan_entitlements_feature_key'), 'commercial_plan_entitlements', ['feature_key'], unique=False)
    op.create_index(op.f('ix_commercial_plan_entitlements_id'), 'commercial_plan_entitlements', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_plan_entitlements_plan_id'), 'commercial_plan_entitlements', ['plan_id'], unique=False)
    op.create_table('commercial_prices',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('interval', enum_type('MONTHLY', 'ANNUAL', name='billinginterval'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['commercial_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_prices_id'), 'commercial_prices', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_prices_plan_id'), 'commercial_prices', ['plan_id'], unique=False)
    op.create_table('commercial_service_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('status', enum_type('CREATED', 'IN_PROGRESS', 'DELIVERED', 'CLOSED', name='orderstatus'), nullable=False),
    sa.Column('assigned_consultant', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('milestones_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['commercial_service_quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_commercial_service_orders_id'), 'commercial_service_orders', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_service_orders_order_number'), 'commercial_service_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_commercial_service_orders_organization_id'), 'commercial_service_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_service_orders_status'), 'commercial_service_orders', ['status'], unique=False)
    op.create_table('commercial_subscription_items',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('external_price_id', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_subscription_items_id'), 'commercial_subscription_items', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_subscription_items_subscription_id'), 'commercial_subscription_items', ['subscription_id'], unique=False)
    op.create_table('commercial_support_messages',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['commercial_support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_support_messages_id'), 'commercial_support_messages', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_support_messages_ticket_id'), 'commercial_support_messages', ['ticket_id'], unique=False)
    op.create_table('commercial_invoice_line_items',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('hsn_sac_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['commercial_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_invoice_line_items_id'), 'commercial_invoice_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_invoice_line_items_invoice_id'), 'commercial_invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('commercial_payments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', enum_type('STRIPE', 'RAZORPAY', 'MANUAL_INVOICE', name='billingprovidertype'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=150), nullable=False),
    sa.Column('status', enum_type('SUCCEEDED', 'PENDING', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['commercial_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_payments_id'), 'commercial_payments', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_payments_invoice_id'), 'commercial_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_commercial_payments_organization_id'), 'commercial_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commercial_payments_transaction_reference'), 'commercial_payments', ['transaction_reference'], unique=True)
    op.create_table('commercial_support_attachments',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['commercial_support_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['commercial_support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_support_attachments_id'), 'commercial_support_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_support_attachments_ticket_id'), 'commercial_support_attachments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commercial_support_attachments_ticket_id'), table_name='commercial_support_attachments')
    op.drop_index(op.f('ix_commercial_support_attachments_id'), table_name='commercial_support_attachments')
    op.drop_table('commercial_support_attachments')
    op.drop_index(op.f('ix_commercial_payments_transaction_reference'), table_name='commercial_payments')
    op.drop_index(op.f('ix_commercial_payments_organization_id'), table_name='commercial_payments')
    op.drop_index(op.f('ix_commercial_payments_invoice_id'), table_name='commercial_payments')
    op.drop_index(op.f('ix_commercial_payments_id'), table_name='commercial_payments')
    op.drop_table('commercial_payments')
    op.drop_index(op.f('ix_commercial_invoice_line_items_invoice_id'), table_name='commercial_invoice_line_items')
    op.drop_index(op.f('ix_commercial_invoice_line_items_id'), table_name='commercial_invoice_line_items')
    op.drop_table('commercial_invoice_line_items')
    op.drop_index(op.f('ix_commercial_support_messages_ticket_id'), table_name='commercial_support_messages')
    op.drop_index(op.f('ix_commercial_support_messages_id'), table_name='commercial_support_messages')
    op.drop_table('commercial_support_messages')
    op.drop_index(op.f('ix_commercial_subscription_items_subscription_id'), table_name='commercial_subscription_items')
    op.drop_index(op.f('ix_commercial_subscription_items_id'), table_name='commercial_subscription_items')
    op.drop_table('commercial_subscription_items')
    op.drop_index(op.f('ix_commercial_service_orders_status'), table_name='commercial_service_orders')
    op.drop_index(op.f('ix_commercial_service_orders_organization_id'), table_name='commercial_service_orders')
    op.drop_index(op.f('ix_commercial_service_orders_order_number'), table_name='commercial_service_orders')
    op.drop_index(op.f('ix_commercial_service_orders_id'), table_name='commercial_service_orders')
    op.drop_table('commercial_service_orders')
    op.drop_index(op.f('ix_commercial_prices_plan_id'), table_name='commercial_prices')
    op.drop_index(op.f('ix_commercial_prices_id'), table_name='commercial_prices')
    op.drop_table('commercial_prices')
    op.drop_index(op.f('ix_commercial_plan_entitlements_plan_id'), table_name='commercial_plan_entitlements')
    op.drop_index(op.f('ix_commercial_plan_entitlements_id'), table_name='commercial_plan_entitlements')
    op.drop_index(op.f('ix_commercial_plan_entitlements_feature_key'), table_name='commercial_plan_entitlements')
    op.drop_table('commercial_plan_entitlements')
    op.drop_index(op.f('ix_commercial_invoices_subscription_id'), table_name='commercial_invoices')
    op.drop_index(op.f('ix_commercial_invoices_status'), table_name='commercial_invoices')
    op.drop_index(op.f('ix_commercial_invoices_organization_id'), table_name='commercial_invoices')
    op.drop_index(op.f('ix_commercial_invoices_invoice_number'), table_name='commercial_invoices')
    op.drop_index(op.f('ix_commercial_invoices_id'), table_name='commercial_invoices')
    op.drop_table('commercial_invoices')
    op.drop_index(op.f('ix_commercial_connector_sync_runs_organization_id'), table_name='commercial_connector_sync_runs')
    op.drop_index(op.f('ix_commercial_connector_sync_runs_id'), table_name='commercial_connector_sync_runs')
    op.drop_index(op.f('ix_commercial_connector_sync_runs_connector_id'), table_name='commercial_connector_sync_runs')
    op.drop_table('commercial_connector_sync_runs')
    op.drop_index(op.f('ix_commercial_user_mfa_credentials_user_id'), table_name='commercial_user_mfa_credentials')
    op.drop_index(op.f('ix_commercial_user_mfa_credentials_id'), table_name='commercial_user_mfa_credentials')
    op.drop_table('commercial_user_mfa_credentials')
    op.drop_index(op.f('ix_commercial_usage_events_organization_id'), table_name='commercial_usage_events')
    op.drop_index(op.f('ix_commercial_usage_events_metric_key'), table_name='commercial_usage_events')
    op.drop_index(op.f('ix_commercial_usage_events_idempotency_key'), table_name='commercial_usage_events')
    op.drop_index(op.f('ix_commercial_usage_events_id'), table_name='commercial_usage_events')
    op.drop_table('commercial_usage_events')
    op.drop_index(op.f('ix_commercial_usage_aggregates_organization_id'), table_name='commercial_usage_aggregates')
    op.drop_index(op.f('ix_commercial_usage_aggregates_metric_key'), table_name='commercial_usage_aggregates')
    op.drop_index(op.f('ix_commercial_usage_aggregates_id'), table_name='commercial_usage_aggregates')
    op.drop_table('commercial_usage_aggregates')
    op.drop_index(op.f('ix_commercial_support_tickets_ticket_number'), table_name='commercial_support_tickets')
    op.drop_index(op.f('ix_commercial_support_tickets_status'), table_name='commercial_support_tickets')
    op.drop_index(op.f('ix_commercial_support_tickets_organization_id'), table_name='commercial_support_tickets')
    op.drop_index(op.f('ix_commercial_support_tickets_id'), table_name='commercial_support_tickets')
    op.drop_table('commercial_support_tickets')
    op.drop_index(op.f('ix_commercial_subscriptions_status'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_organization_id'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_id'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_external_subscription_id'), table_name='commercial_subscriptions')
    op.drop_table('commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_service_quotes_status'), table_name='commercial_service_quotes')
    op.drop_index(op.f('ix_commercial_service_quotes_quote_number'), table_name='commercial_service_quotes')
    op.drop_index(op.f('ix_commercial_service_quotes_organization_id'), table_name='commercial_service_quotes')
    op.drop_index(op.f('ix_commercial_service_quotes_id'), table_name='commercial_service_quotes')
    op.drop_table('commercial_service_quotes')
    op.drop_index(op.f('ix_commercial_product_events_organization_id'), table_name='commercial_product_events')
    op.drop_index(op.f('ix_commercial_product_events_id'), table_name='commercial_product_events')
    op.drop_index(op.f('ix_commercial_product_events_event_name'), table_name='commercial_product_events')
    op.drop_table('commercial_product_events')
    op.drop_index(op.f('ix_commercial_plans_tier'), table_name='commercial_plans')
    op.drop_index(op.f('ix_commercial_plans_product_id'), table_name='commercial_plans')
    op.drop_index(op.f('ix_commercial_plans_id'), table_name='commercial_plans')
    op.drop_table('commercial_plans')
    op.drop_index(op.f('ix_commercial_password_reset_tokens_user_id'), table_name='commercial_password_reset_tokens')
    op.drop_index(op.f('ix_commercial_password_reset_tokens_token_hash'), table_name='commercial_password_reset_tokens')
    op.drop_index(op.f('ix_commercial_password_reset_tokens_id'), table_name='commercial_password_reset_tokens')
    op.drop_table('commercial_password_reset_tokens')
    op.drop_index(op.f('ix_commercial_organization_profiles_organization_id'), table_name='commercial_organization_profiles')
    op.drop_index(op.f('ix_commercial_organization_profiles_id'), table_name='commercial_organization_profiles')
    op.drop_index(op.f('ix_commercial_organization_profiles_gstin'), table_name='commercial_organization_profiles')
    op.drop_table('commercial_organization_profiles')
    op.drop_index(op.f('ix_commercial_organization_entitlements_organization_id'), table_name='commercial_organization_entitlements')
    op.drop_index(op.f('ix_commercial_organization_entitlements_id'), table_name='commercial_organization_entitlements')
    op.drop_index(op.f('ix_commercial_organization_entitlements_feature_key'), table_name='commercial_organization_entitlements')
    op.drop_table('commercial_organization_entitlements')
    op.drop_index(op.f('ix_commercial_onboarding_states_organization_id'), table_name='commercial_onboarding_states')
    op.drop_index(op.f('ix_commercial_onboarding_states_id'), table_name='commercial_onboarding_states')
    op.drop_table('commercial_onboarding_states')
    op.drop_index(op.f('ix_commercial_invitations_token_hash'), table_name='commercial_invitations')
    op.drop_index(op.f('ix_commercial_invitations_status'), table_name='commercial_invitations')
    op.drop_index(op.f('ix_commercial_invitations_organization_id'), table_name='commercial_invitations')
    op.drop_index(op.f('ix_commercial_invitations_id'), table_name='commercial_invitations')
    op.drop_index(op.f('ix_commercial_invitations_email'), table_name='commercial_invitations')
    op.drop_table('commercial_invitations')
    op.drop_index(op.f('ix_commercial_evidence_connectors_status'), table_name='commercial_evidence_connectors')
    op.drop_index(op.f('ix_commercial_evidence_connectors_organization_id'), table_name='commercial_evidence_connectors')
    op.drop_index(op.f('ix_commercial_evidence_connectors_id'), table_name='commercial_evidence_connectors')
    op.drop_index(op.f('ix_commercial_evidence_connectors_connector_type'), table_name='commercial_evidence_connectors')
    op.drop_table('commercial_evidence_connectors')
    op.drop_index(op.f('ix_commercial_email_verification_tokens_user_id'), table_name='commercial_email_verification_tokens')
    op.drop_index(op.f('ix_commercial_email_verification_tokens_token_hash'), table_name='commercial_email_verification_tokens')
    op.drop_index(op.f('ix_commercial_email_verification_tokens_id'), table_name='commercial_email_verification_tokens')
    op.drop_table('commercial_email_verification_tokens')
    op.drop_index(op.f('ix_commercial_customer_success_tasks_organization_id'), table_name='commercial_customer_success_tasks')
    op.drop_index(op.f('ix_commercial_customer_success_tasks_id'), table_name='commercial_customer_success_tasks')
    op.drop_table('commercial_customer_success_tasks')
    op.drop_index(op.f('ix_commercial_customer_success_health_status'), table_name='commercial_customer_success_health')
    op.drop_index(op.f('ix_commercial_customer_success_health_organization_id'), table_name='commercial_customer_success_health')
    op.drop_index(op.f('ix_commercial_customer_success_health_id'), table_name='commercial_customer_success_health')
    op.drop_table('commercial_customer_success_health')
    op.drop_index(op.f('ix_commercial_crm_opportunities_stage'), table_name='commercial_crm_opportunities')
    op.drop_index(op.f('ix_commercial_crm_opportunities_organization_id'), table_name='commercial_crm_opportunities')
    op.drop_index(op.f('ix_commercial_crm_opportunities_id'), table_name='commercial_crm_opportunities')
    op.drop_table('commercial_crm_opportunities')
    op.drop_index(op.f('ix_commercial_billing_customers_stripe_customer_id'), table_name='commercial_billing_customers')
    op.drop_index(op.f('ix_commercial_billing_customers_razorpay_customer_id'), table_name='commercial_billing_customers')
    op.drop_index(op.f('ix_commercial_billing_customers_organization_id'), table_name='commercial_billing_customers')
    op.drop_index(op.f('ix_commercial_billing_customers_id'), table_name='commercial_billing_customers')
    op.drop_table('commercial_billing_customers')
    op.drop_index(op.f('ix_commercial_auditor_evidence_comments_organization_id'), table_name='commercial_auditor_evidence_comments')
    op.drop_index(op.f('ix_commercial_auditor_evidence_comments_id'), table_name='commercial_auditor_evidence_comments')
    op.drop_index(op.f('ix_commercial_auditor_evidence_comments_evidence_request_id'), table_name='commercial_auditor_evidence_comments')
    op.drop_index(op.f('ix_commercial_auditor_evidence_comments_evidence_id'), table_name='commercial_auditor_evidence_comments')
    op.drop_table('commercial_auditor_evidence_comments')
    op.drop_index(op.f('ix_commercial_usage_metric_definitions_metric_key'), table_name='commercial_usage_metric_definitions')
    op.drop_index(op.f('ix_commercial_usage_metric_definitions_id'), table_name='commercial_usage_metric_definitions')
    op.drop_table('commercial_usage_metric_definitions')
    op.drop_index(op.f('ix_commercial_support_slas_plan_tier'), table_name='commercial_support_slas')
    op.drop_index(op.f('ix_commercial_support_slas_id'), table_name='commercial_support_slas')
    op.drop_table('commercial_support_slas')
    op.drop_index(op.f('ix_commercial_status_incidents_state'), table_name='commercial_status_incidents')
    op.drop_index(op.f('ix_commercial_status_incidents_id'), table_name='commercial_status_incidents')
    op.drop_table('commercial_status_incidents')
    op.drop_index(op.f('ix_commercial_products_product_code'), table_name='commercial_products')
    op.drop_index(op.f('ix_commercial_products_id'), table_name='commercial_products')
    op.drop_table('commercial_products')
    op.drop_index(op.f('ix_commercial_platform_settings_key'), table_name='commercial_platform_settings')
    op.drop_index(op.f('ix_commercial_platform_settings_id'), table_name='commercial_platform_settings')
    op.drop_table('commercial_platform_settings')
    op.drop_index(op.f('ix_commercial_feature_flags_key'), table_name='commercial_feature_flags')
    op.drop_index(op.f('ix_commercial_feature_flags_id'), table_name='commercial_feature_flags')
    op.drop_table('commercial_feature_flags')
    op.drop_index(op.f('ix_commercial_feature_flag_overrides_scope_id'), table_name='commercial_feature_flag_overrides')
    op.drop_index(op.f('ix_commercial_feature_flag_overrides_id'), table_name='commercial_feature_flag_overrides')
    op.drop_index(op.f('ix_commercial_feature_flag_overrides_flag_key'), table_name='commercial_feature_flag_overrides')
    op.drop_table('commercial_feature_flag_overrides')
    op.drop_index(op.f('ix_commercial_crm_leads_status'), table_name='commercial_crm_leads')
    op.drop_index(op.f('ix_commercial_crm_leads_id'), table_name='commercial_crm_leads')
    op.drop_index(op.f('ix_commercial_crm_leads_email'), table_name='commercial_crm_leads')
    op.drop_table('commercial_crm_leads')
    op.drop_index(op.f('ix_commercial_coupons_id'), table_name='commercial_coupons')
    op.drop_index(op.f('ix_commercial_coupons_code'), table_name='commercial_coupons')
    op.drop_table('commercial_coupons')
    # ### end Alembic commands ###
