"""phase9_real_production_launch_and_hardening

Revision ID: 5dd2bef950f7
Revises: 2ee537f7dc1f
Create Date: 2026-10-03 17:26:45.531321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.migration_types import enum_type


# revision identifiers, used by Alembic.
revision: str = '5dd2bef950f7'
down_revision: Union[str, Sequence[str], None] = '2ee537f7dc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_email_bounces',
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('bounce_type', enum_type('PERMANENT_BOUNCE', 'TRANSIENT_BOUNCE', 'COMPLAINT', 'SUPPRESSION', name='bouncetype'), nullable=False),
    sa.Column('complaint_feedback', sa.Text(), nullable=True),
    sa.Column('raw_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_email_bounces_id'), 'production_email_bounces', ['id'], unique=False)
    op.create_index(op.f('ix_production_email_bounces_recipient_email'), 'production_email_bounces', ['recipient_email'], unique=True)
    op.create_table('production_launch_approvals',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('decision', enum_type('GO', 'GO_WITH_WARNINGS', 'NO_GO', name='launchdecision'), nullable=False),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_launch_approvals_decision'), 'production_launch_approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_production_launch_approvals_id'), 'production_launch_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_production_launch_approvals_version'), 'production_launch_approvals', ['version'], unique=False)
    op.create_table('production_payment_webhook_events',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', enum_type('RECEIVED', 'VERIFIED', 'PROCESSED', 'FAILED', 'IGNORED', name='webhookprocessingstatus'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_payment_webhook_events_event_type'), 'production_payment_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_production_payment_webhook_events_id'), 'production_payment_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_production_payment_webhook_events_provider'), 'production_payment_webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_production_payment_webhook_events_provider_event_id'), 'production_payment_webhook_events', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_production_payment_webhook_events_status'), 'production_payment_webhook_events', ['status'], unique=False)
    op.create_table('production_provider_price_mappings',
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_product_id', sa.String(length=100), nullable=False),
    sa.Column('provider_price_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_provider_price_mappings_id'), 'production_provider_price_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_production_provider_price_mappings_plan_tier'), 'production_provider_price_mappings', ['plan_tier'], unique=False)
    op.create_index(op.f('ix_production_provider_price_mappings_provider_price_id'), 'production_provider_price_mappings', ['provider_price_id'], unique=False)
    op.create_table('production_restore_rehearsals',
    sa.Column('snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('target_environment', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rto_seconds', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_restore_rehearsals_id'), 'production_restore_rehearsals', ['id'], unique=False)
    op.create_table('production_break_glass_access',
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_break_glass_access_admin_user_id'), 'production_break_glass_access', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_production_break_glass_access_id'), 'production_break_glass_access', ['id'], unique=False)
    op.create_table('production_customer_acceptance',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('acceptance_date', sa.DateTime(), nullable=False),
    sa.Column('validated_items_json', sa.Text(), nullable=False),
    sa.Column('open_items_json', sa.Text(), nullable=False),
    sa.Column('customer_contact', sa.String(length=255), nullable=False),
    sa.Column('internal_owner', sa.String(length=255), nullable=False),
    sa.Column('sign_off_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_customer_acceptance_id'), 'production_customer_acceptance', ['id'], unique=False)
    op.create_index(op.f('ix_production_customer_acceptance_organization_id'), 'production_customer_acceptance', ['organization_id'], unique=True)
    op.create_table('production_customer_feedback',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('release_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_customer_feedback_id'), 'production_customer_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_production_customer_feedback_organization_id'), 'production_customer_feedback', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_customer_feedback_organization_id'), table_name='production_customer_feedback')
    op.drop_index(op.f('ix_production_customer_feedback_id'), table_name='production_customer_feedback')
    op.drop_table('production_customer_feedback')
    op.drop_index(op.f('ix_production_customer_acceptance_organization_id'), table_name='production_customer_acceptance')
    op.drop_index(op.f('ix_production_customer_acceptance_id'), table_name='production_customer_acceptance')
    op.drop_table('production_customer_acceptance')
    op.drop_index(op.f('ix_production_break_glass_access_id'), table_name='production_break_glass_access')
    op.drop_index(op.f('ix_production_break_glass_access_admin_user_id'), table_name='production_break_glass_access')
    op.drop_table('production_break_glass_access')
    op.drop_index(op.f('ix_production_restore_rehearsals_id'), table_name='production_restore_rehearsals')
    op.drop_table('production_restore_rehearsals')
    op.drop_index(op.f('ix_production_provider_price_mappings_provider_price_id'), table_name='production_provider_price_mappings')
    op.drop_index(op.f('ix_production_provider_price_mappings_plan_tier'), table_name='production_provider_price_mappings')
    op.drop_index(op.f('ix_production_provider_price_mappings_id'), table_name='production_provider_price_mappings')
    op.drop_table('production_provider_price_mappings')
    op.drop_index(op.f('ix_production_payment_webhook_events_status'), table_name='production_payment_webhook_events')
    op.drop_index(op.f('ix_production_payment_webhook_events_provider_event_id'), table_name='production_payment_webhook_events')
    op.drop_index(op.f('ix_production_payment_webhook_events_provider'), table_name='production_payment_webhook_events')
    op.drop_index(op.f('ix_production_payment_webhook_events_id'), table_name='production_payment_webhook_events')
    op.drop_index(op.f('ix_production_payment_webhook_events_event_type'), table_name='production_payment_webhook_events')
    op.drop_table('production_payment_webhook_events')
    op.drop_index(op.f('ix_production_launch_approvals_version'), table_name='production_launch_approvals')
    op.drop_index(op.f('ix_production_launch_approvals_id'), table_name='production_launch_approvals')
    op.drop_index(op.f('ix_production_launch_approvals_decision'), table_name='production_launch_approvals')
    op.drop_table('production_launch_approvals')
    op.drop_index(op.f('ix_production_email_bounces_recipient_email'), table_name='production_email_bounces')
    op.drop_index(op.f('ix_production_email_bounces_id'), table_name='production_email_bounces')
    op.drop_table('production_email_bounces')
    # ### end Alembic commands ###
