"""phase11_continuous_assurance_bots_overlay_workpapers

Revision ID: 7ad6261cb495
Revises: b65aff726dc6
Create Date: 2026-10-03 23:02:59.614252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.migration_types import enum_type


# revision identifiers, used by Alembic.
revision: str = '7ad6261cb495'
down_revision: Union[str, Sequence[str], None] = 'b65aff726dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assurance_automation_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_trigger', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assurance_automation_policies_id'), 'assurance_automation_policies', ['id'], unique=False)
    op.create_index(op.f('ix_assurance_automation_policies_organization_id'), 'assurance_automation_policies', ['organization_id'], unique=False)
    op.create_table('audit_bots',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('bot_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_control_code', sa.String(length=100), nullable=False),
    sa.Column('schedule', enum_type('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'ON_RELEASE', 'ON_CHANGE', 'MANUAL', name='auditbotschedule'), nullable=False),
    sa.Column('status', enum_type('DRAFT', 'ENABLED', 'RUNNING', 'PASS', 'PARTIAL', 'FAIL', 'ERROR', 'DISABLED', name='auditbotstatus'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('execution_config_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_bots_bot_code'), 'audit_bots', ['bot_code'], unique=False)
    op.create_index(op.f('ix_audit_bots_id'), 'audit_bots', ['id'], unique=False)
    op.create_index(op.f('ix_audit_bots_organization_id'), 'audit_bots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_bots_target_control_code'), 'audit_bots', ['target_control_code'], unique=False)
    op.create_table('auditor_workpapers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('workpaper_number', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('auditor_email', sa.String(length=255), nullable=False),
    sa.Column('review_status', enum_type('NOT_REVIEWED', 'IN_REVIEW', 'ACCEPTED', 'REJECTED', 'NEEDS_MORE_INFO', name='auditorreviewstatus'), nullable=False),
    sa.Column('sampling_notes', sa.Text(), nullable=True),
    sa.Column('findings_notes', sa.Text(), nullable=True),
    sa.Column('evidence_references_json', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['auditor_access_grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_workpapers_control_code'), 'auditor_workpapers', ['control_code'], unique=False)
    op.create_index(op.f('ix_auditor_workpapers_grant_id'), 'auditor_workpapers', ['grant_id'], unique=False)
    op.create_index(op.f('ix_auditor_workpapers_id'), 'auditor_workpapers', ['id'], unique=False)
    op.create_index(op.f('ix_auditor_workpapers_organization_id'), 'auditor_workpapers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auditor_workpapers_review_status'), 'auditor_workpapers', ['review_status'], unique=False)
    op.create_index(op.f('ix_auditor_workpapers_workpaper_number'), 'auditor_workpapers', ['workpaper_number'], unique=False)
    op.create_table('continuous_control_monitors',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('current_status', enum_type('PASS', 'PARTIAL', 'FAIL', 'STALE', 'ERROR', 'NOT_MONITORED', name='continuouscontrolstatus'), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('next_evaluation_at', sa.DateTime(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('evidence_used_json', sa.Text(), nullable=False),
    sa.Column('evidence_missing_json', sa.Text(), nullable=False),
    sa.Column('operating_evidence_count', sa.Integer(), nullable=False),
    sa.Column('total_evaluations_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continuous_control_monitors_control_code'), 'continuous_control_monitors', ['control_code'], unique=False)
    op.create_index(op.f('ix_continuous_control_monitors_current_status'), 'continuous_control_monitors', ['current_status'], unique=False)
    op.create_index(op.f('ix_continuous_control_monitors_id'), 'continuous_control_monitors', ['id'], unique=False)
    op.create_index(op.f('ix_continuous_control_monitors_organization_id'), 'continuous_control_monitors', ['organization_id'], unique=False)
    op.create_table('control_evaluation_histories',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('evidence_observation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_evaluation_histories_control_code'), 'control_evaluation_histories', ['control_code'], unique=False)
    op.create_index(op.f('ix_control_evaluation_histories_id'), 'control_evaluation_histories', ['id'], unique=False)
    op.create_index(op.f('ix_control_evaluation_histories_organization_id'), 'control_evaluation_histories', ['organization_id'], unique=False)
    op.create_table('evidence_freshness_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_class', sa.String(length=100), nullable=False),
    sa.Column('max_age_hours', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_freshness_policies_evidence_class'), 'evidence_freshness_policies', ['evidence_class'], unique=False)
    op.create_index(op.f('ix_evidence_freshness_policies_id'), 'evidence_freshness_policies', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_freshness_policies_organization_id'), 'evidence_freshness_policies', ['organization_id'], unique=False)
    op.create_table('evidence_observations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_code', sa.String(length=100), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('external_resource_id', sa.String(length=255), nullable=False),
    sa.Column('collector_version', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('authenticity_status', enum_type('VERIFIED_SOURCE', 'SIGNED_SOURCE', 'API_COLLECTED', 'MANUAL_UPLOAD', 'UNVERIFIED', 'REJECTED', name='evidenceauthenticitystatus'), nullable=False),
    sa.Column('freshness_status', enum_type('CURRENT', 'EXPIRING', 'STALE', 'MISSING', 'INVALID', name='evidencefreshnessstatus'), nullable=False),
    sa.Column('normalized_data_json', sa.Text(), nullable=False),
    sa.Column('provenance_metadata_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_observations_control_code'), 'evidence_observations', ['control_code'], unique=False)
    op.create_index(op.f('ix_evidence_observations_evidence_code'), 'evidence_observations', ['evidence_code'], unique=False)
    op.create_index(op.f('ix_evidence_observations_external_resource_id'), 'evidence_observations', ['external_resource_id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_id'), 'evidence_observations', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_organization_id'), 'evidence_observations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_source_provider'), 'evidence_observations', ['source_provider'], unique=False)
    op.create_table('partner_custom_domains',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('dns_verification_token', sa.String(length=100), nullable=False),
    sa.Column('cname_target', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('tls_status', enum_type('PENDING_VERIFICATION', 'VERIFIED', 'CERTIFICATE_PENDING', 'ACTIVE', 'ERROR', 'SUSPENDED', name='customdomaintlsstatus'), nullable=False),
    sa.Column('certificate_arn', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_custom_domains_domain_name'), 'partner_custom_domains', ['domain_name'], unique=True)
    op.create_index(op.f('ix_partner_custom_domains_id'), 'partner_custom_domains', ['id'], unique=False)
    op.create_index(op.f('ix_partner_custom_domains_partner_id'), 'partner_custom_domains', ['partner_id'], unique=False)
    op.create_table('partner_email_brandings',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('reply_to', sa.String(length=255), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('dkim_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_email_brandings_id'), 'partner_email_brandings', ['id'], unique=False)
    op.create_index(op.f('ix_partner_email_brandings_partner_id'), 'partner_email_brandings', ['partner_id'], unique=False)
    op.create_table('audit_bot_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('raw_output_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('records_scanned', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['audit_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_bot_runs_bot_id'), 'audit_bot_runs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_audit_bot_runs_id'), 'audit_bot_runs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_bot_runs_organization_id'), 'audit_bot_runs', ['organization_id'], unique=False)
    op.create_table('auditor_evidence_review_threads',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workpaper_id', sa.String(length=36), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workpaper_id'], ['auditor_workpapers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_evidence_review_threads_id'), 'auditor_evidence_review_threads', ['id'], unique=False)
    op.create_index(op.f('ix_auditor_evidence_review_threads_organization_id'), 'auditor_evidence_review_threads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auditor_evidence_review_threads_workpaper_id'), 'auditor_evidence_review_threads', ['workpaper_id'], unique=False)
    op.create_table('evidence_integrity_chains',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_observation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('chained_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_observation_id'], ['evidence_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_integrity_chains_evidence_observation_id'), 'evidence_integrity_chains', ['evidence_observation_id'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_chains_id'), 'evidence_integrity_chains', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_chains_organization_id'), 'evidence_integrity_chains', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_chains_sequence_number'), 'evidence_integrity_chains', ['sequence_number'], unique=False)
    op.create_table('audit_bot_observations',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('check_name', sa.String(length=255), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('observed_state_json', sa.Text(), nullable=False),
    sa.Column('remediation_hint', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_bot_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_bot_observations_id'), 'audit_bot_observations', ['id'], unique=False)
    op.create_index(op.f('ix_audit_bot_observations_resource_id'), 'audit_bot_observations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_bot_observations_run_id'), 'audit_bot_observations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_bot_observations_run_id'), table_name='audit_bot_observations')
    op.drop_index(op.f('ix_audit_bot_observations_resource_id'), table_name='audit_bot_observations')
    op.drop_index(op.f('ix_audit_bot_observations_id'), table_name='audit_bot_observations')
    op.drop_table('audit_bot_observations')
    op.drop_index(op.f('ix_evidence_integrity_chains_sequence_number'), table_name='evidence_integrity_chains')
    op.drop_index(op.f('ix_evidence_integrity_chains_organization_id'), table_name='evidence_integrity_chains')
    op.drop_index(op.f('ix_evidence_integrity_chains_id'), table_name='evidence_integrity_chains')
    op.drop_index(op.f('ix_evidence_integrity_chains_evidence_observation_id'), table_name='evidence_integrity_chains')
    op.drop_table('evidence_integrity_chains')
    op.drop_index(op.f('ix_auditor_evidence_review_threads_workpaper_id'), table_name='auditor_evidence_review_threads')
    op.drop_index(op.f('ix_auditor_evidence_review_threads_organization_id'), table_name='auditor_evidence_review_threads')
    op.drop_index(op.f('ix_auditor_evidence_review_threads_id'), table_name='auditor_evidence_review_threads')
    op.drop_table('auditor_evidence_review_threads')
    op.drop_index(op.f('ix_audit_bot_runs_organization_id'), table_name='audit_bot_runs')
    op.drop_index(op.f('ix_audit_bot_runs_id'), table_name='audit_bot_runs')
    op.drop_index(op.f('ix_audit_bot_runs_bot_id'), table_name='audit_bot_runs')
    op.drop_table('audit_bot_runs')
    op.drop_index(op.f('ix_partner_email_brandings_partner_id'), table_name='partner_email_brandings')
    op.drop_index(op.f('ix_partner_email_brandings_id'), table_name='partner_email_brandings')
    op.drop_table('partner_email_brandings')
    op.drop_index(op.f('ix_partner_custom_domains_partner_id'), table_name='partner_custom_domains')
    op.drop_index(op.f('ix_partner_custom_domains_id'), table_name='partner_custom_domains')
    op.drop_index(op.f('ix_partner_custom_domains_domain_name'), table_name='partner_custom_domains')
    op.drop_table('partner_custom_domains')
    op.drop_index(op.f('ix_evidence_observations_source_provider'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_organization_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_external_resource_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_evidence_code'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_control_code'), table_name='evidence_observations')
    op.drop_table('evidence_observations')
    op.drop_index(op.f('ix_evidence_freshness_policies_organization_id'), table_name='evidence_freshness_policies')
    op.drop_index(op.f('ix_evidence_freshness_policies_id'), table_name='evidence_freshness_policies')
    op.drop_index(op.f('ix_evidence_freshness_policies_evidence_class'), table_name='evidence_freshness_policies')
    op.drop_table('evidence_freshness_policies')
    op.drop_index(op.f('ix_control_evaluation_histories_organization_id'), table_name='control_evaluation_histories')
    op.drop_index(op.f('ix_control_evaluation_histories_id'), table_name='control_evaluation_histories')
    op.drop_index(op.f('ix_control_evaluation_histories_control_code'), table_name='control_evaluation_histories')
    op.drop_table('control_evaluation_histories')
    op.drop_index(op.f('ix_continuous_control_monitors_organization_id'), table_name='continuous_control_monitors')
    op.drop_index(op.f('ix_continuous_control_monitors_id'), table_name='continuous_control_monitors')
    op.drop_index(op.f('ix_continuous_control_monitors_current_status'), table_name='continuous_control_monitors')
    op.drop_index(op.f('ix_continuous_control_monitors_control_code'), table_name='continuous_control_monitors')
    op.drop_table('continuous_control_monitors')
    op.drop_index(op.f('ix_auditor_workpapers_workpaper_number'), table_name='auditor_workpapers')
    op.drop_index(op.f('ix_auditor_workpapers_review_status'), table_name='auditor_workpapers')
    op.drop_index(op.f('ix_auditor_workpapers_organization_id'), table_name='auditor_workpapers')
    op.drop_index(op.f('ix_auditor_workpapers_id'), table_name='auditor_workpapers')
    op.drop_index(op.f('ix_auditor_workpapers_grant_id'), table_name='auditor_workpapers')
    op.drop_index(op.f('ix_auditor_workpapers_control_code'), table_name='auditor_workpapers')
    op.drop_table('auditor_workpapers')
    op.drop_index(op.f('ix_audit_bots_target_control_code'), table_name='audit_bots')
    op.drop_index(op.f('ix_audit_bots_organization_id'), table_name='audit_bots')
    op.drop_index(op.f('ix_audit_bots_id'), table_name='audit_bots')
    op.drop_index(op.f('ix_audit_bots_bot_code'), table_name='audit_bots')
    op.drop_table('audit_bots')
    op.drop_index(op.f('ix_assurance_automation_policies_organization_id'), table_name='assurance_automation_policies')
    op.drop_index(op.f('ix_assurance_automation_policies_id'), table_name='assurance_automation_policies')
    op.drop_table('assurance_automation_policies')
    # ### end Alembic commands ###
