"""phase4_release_delivery_engine

Revision ID: 8eae332883a4
Revises: 91e6bf385da8
Create Date: 2026-10-01 17:31:52.868179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eae332883a4'
down_revision: Union[str, Sequence[str], None] = '91e6bf385da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_releases',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_of_release_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_releases_application_id'), 'application_releases', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_releases_commit_sha'), 'application_releases', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_application_releases_environment_id'), 'application_releases', ['environment_id'], unique=False)
    op.create_index(op.f('ix_application_releases_id'), 'application_releases', ['id'], unique=False)
    op.create_index(op.f('ix_application_releases_organization_id'), 'application_releases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_application_releases_status'), 'application_releases', ['status'], unique=False)
    op.create_index(op.f('ix_application_releases_version'), 'application_releases', ['version'], unique=False)
    op.create_table('domain_bindings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('dns_provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_bindings_application_id'), 'domain_bindings', ['application_id'], unique=False)
    op.create_index(op.f('ix_domain_bindings_domain'), 'domain_bindings', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_bindings_environment_id'), 'domain_bindings', ['environment_id'], unique=False)
    op.create_index(op.f('ix_domain_bindings_id'), 'domain_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_domain_bindings_organization_id'), 'domain_bindings', ['organization_id'], unique=False)
    op.create_table('runtime_secret_bindings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('environment_variable_name', sa.String(length=255), nullable=False),
    sa.Column('secrets_manager_arn', sa.String(length=500), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_secret_bindings_environment_id'), 'runtime_secret_bindings', ['environment_id'], unique=False)
    op.create_index(op.f('ix_runtime_secret_bindings_id'), 'runtime_secret_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_runtime_secret_bindings_organization_id'), 'runtime_secret_bindings', ['organization_id'], unique=False)
    op.create_table('application_deployments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_release_id', sa.String(length=36), nullable=True),
    sa.Column('target_release_id', sa.String(length=36), nullable=False),
    sa.Column('traffic_percentage', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_deployments_application_release_id'), 'application_deployments', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_application_deployments_environment_id'), 'application_deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_application_deployments_id'), 'application_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_application_deployments_organization_id'), 'application_deployments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_application_deployments_status'), 'application_deployments', ['status'], unique=False)
    op.create_table('build_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('worker_job_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('builder_version', sa.String(length=50), nullable=False),
    sa.Column('source_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_runs_application_release_id'), 'build_runs', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_build_runs_id'), 'build_runs', ['id'], unique=False)
    op.create_index(op.f('ix_build_runs_organization_id'), 'build_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_build_runs_status'), 'build_runs', ['status'], unique=False)
    op.create_table('certificate_records',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain_binding_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('certificate_arn', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('validation_method', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_binding_id'], ['domain_bindings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_records_domain_binding_id'), 'certificate_records', ['domain_binding_id'], unique=False)
    op.create_index(op.f('ix_certificate_records_id'), 'certificate_records', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_records_organization_id'), 'certificate_records', ['organization_id'], unique=False)
    op.create_table('container_images',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('ecr_repository', sa.String(length=255), nullable=False),
    sa.Column('image_tag', sa.String(length=100), nullable=False),
    sa.Column('image_digest', sa.String(length=128), nullable=False),
    sa.Column('scan_status', sa.String(length=50), nullable=False),
    sa.Column('critical_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('high_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('medium_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_images_application_release_id'), 'container_images', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_container_images_id'), 'container_images', ['id'], unique=False)
    op.create_index(op.f('ix_container_images_organization_id'), 'container_images', ['organization_id'], unique=False)
    op.create_table('database_migration_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('migration_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('migration_version_before', sa.String(length=100), nullable=True),
    sa.Column('migration_version_after', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_migration_runs_application_release_id'), 'database_migration_runs', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_database_migration_runs_environment_id'), 'database_migration_runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_database_migration_runs_id'), 'database_migration_runs', ['id'], unique=False)
    op.create_index(op.f('ix_database_migration_runs_organization_id'), 'database_migration_runs', ['organization_id'], unique=False)
    op.create_table('release_evidences',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('artifact_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_evidences_application_release_id'), 'release_evidences', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_release_evidences_id'), 'release_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_release_evidences_organization_id'), 'release_evidences', ['organization_id'], unique=False)
    op.create_table('release_verifications',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_release_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_release_id'], ['application_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_verifications_application_release_id'), 'release_verifications', ['application_release_id'], unique=False)
    op.create_index(op.f('ix_release_verifications_environment_id'), 'release_verifications', ['environment_id'], unique=False)
    op.create_index(op.f('ix_release_verifications_id'), 'release_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_release_verifications_organization_id'), 'release_verifications', ['organization_id'], unique=False)
    op.create_table('build_artifacts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('build_run_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('image_repository', sa.String(length=255), nullable=False),
    sa.Column('image_tag', sa.String(length=100), nullable=False),
    sa.Column('image_digest', sa.String(length=128), nullable=False),
    sa.Column('sbom_key', sa.String(length=500), nullable=True),
    sa.Column('manifest_key', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_run_id'], ['build_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_artifacts_build_run_id'), 'build_artifacts', ['build_run_id'], unique=False)
    op.create_index(op.f('ix_build_artifacts_id'), 'build_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_build_artifacts_image_digest'), 'build_artifacts', ['image_digest'], unique=False)
    op.create_index(op.f('ix_build_artifacts_organization_id'), 'build_artifacts', ['organization_id'], unique=False)
    op.create_table('deployment_services',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_deployment_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('ecs_service_arn', sa.String(length=500), nullable=True),
    sa.Column('task_definition_arn', sa.String(length=500), nullable=True),
    sa.Column('desired_count', sa.Integer(), nullable=False),
    sa.Column('running_count', sa.Integer(), nullable=False),
    sa.Column('healthy_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_deployment_id'], ['application_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_services_application_deployment_id'), 'deployment_services', ['application_deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_services_id'), 'deployment_services', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_services_organization_id'), 'deployment_services', ['organization_id'], unique=False)
    op.create_table('rollback_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_deployment_id', sa.String(length=36), nullable=False),
    sa.Column('rollback_to_release_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_deployment_id'], ['application_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollback_runs_application_deployment_id'), 'rollback_runs', ['application_deployment_id'], unique=False)
    op.create_index(op.f('ix_rollback_runs_id'), 'rollback_runs', ['id'], unique=False)
    op.create_index(op.f('ix_rollback_runs_organization_id'), 'rollback_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rollback_runs_rollback_to_release_id'), 'rollback_runs', ['rollback_to_release_id'], unique=False)
    op.create_table('traffic_shifts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_deployment_id', sa.String(length=36), nullable=False),
    sa.Column('from_target', sa.String(length=100), nullable=False),
    sa.Column('to_target', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_deployment_id'], ['application_deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_shifts_application_deployment_id'), 'traffic_shifts', ['application_deployment_id'], unique=False)
    op.create_index(op.f('ix_traffic_shifts_id'), 'traffic_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_shifts_organization_id'), 'traffic_shifts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_shifts_organization_id'), table_name='traffic_shifts')
    op.drop_index(op.f('ix_traffic_shifts_id'), table_name='traffic_shifts')
    op.drop_index(op.f('ix_traffic_shifts_application_deployment_id'), table_name='traffic_shifts')
    op.drop_table('traffic_shifts')
    op.drop_index(op.f('ix_rollback_runs_rollback_to_release_id'), table_name='rollback_runs')
    op.drop_index(op.f('ix_rollback_runs_organization_id'), table_name='rollback_runs')
    op.drop_index(op.f('ix_rollback_runs_id'), table_name='rollback_runs')
    op.drop_index(op.f('ix_rollback_runs_application_deployment_id'), table_name='rollback_runs')
    op.drop_table('rollback_runs')
    op.drop_index(op.f('ix_deployment_services_organization_id'), table_name='deployment_services')
    op.drop_index(op.f('ix_deployment_services_id'), table_name='deployment_services')
    op.drop_index(op.f('ix_deployment_services_application_deployment_id'), table_name='deployment_services')
    op.drop_table('deployment_services')
    op.drop_index(op.f('ix_build_artifacts_organization_id'), table_name='build_artifacts')
    op.drop_index(op.f('ix_build_artifacts_image_digest'), table_name='build_artifacts')
    op.drop_index(op.f('ix_build_artifacts_id'), table_name='build_artifacts')
    op.drop_index(op.f('ix_build_artifacts_build_run_id'), table_name='build_artifacts')
    op.drop_table('build_artifacts')
    op.drop_index(op.f('ix_release_verifications_organization_id'), table_name='release_verifications')
    op.drop_index(op.f('ix_release_verifications_id'), table_name='release_verifications')
    op.drop_index(op.f('ix_release_verifications_environment_id'), table_name='release_verifications')
    op.drop_index(op.f('ix_release_verifications_application_release_id'), table_name='release_verifications')
    op.drop_table('release_verifications')
    op.drop_index(op.f('ix_release_evidences_organization_id'), table_name='release_evidences')
    op.drop_index(op.f('ix_release_evidences_id'), table_name='release_evidences')
    op.drop_index(op.f('ix_release_evidences_application_release_id'), table_name='release_evidences')
    op.drop_table('release_evidences')
    op.drop_index(op.f('ix_database_migration_runs_organization_id'), table_name='database_migration_runs')
    op.drop_index(op.f('ix_database_migration_runs_id'), table_name='database_migration_runs')
    op.drop_index(op.f('ix_database_migration_runs_environment_id'), table_name='database_migration_runs')
    op.drop_index(op.f('ix_database_migration_runs_application_release_id'), table_name='database_migration_runs')
    op.drop_table('database_migration_runs')
    op.drop_index(op.f('ix_container_images_organization_id'), table_name='container_images')
    op.drop_index(op.f('ix_container_images_id'), table_name='container_images')
    op.drop_index(op.f('ix_container_images_application_release_id'), table_name='container_images')
    op.drop_table('container_images')
    op.drop_index(op.f('ix_certificate_records_organization_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_domain_binding_id'), table_name='certificate_records')
    op.drop_table('certificate_records')
    op.drop_index(op.f('ix_build_runs_status'), table_name='build_runs')
    op.drop_index(op.f('ix_build_runs_organization_id'), table_name='build_runs')
    op.drop_index(op.f('ix_build_runs_id'), table_name='build_runs')
    op.drop_index(op.f('ix_build_runs_application_release_id'), table_name='build_runs')
    op.drop_table('build_runs')
    op.drop_index(op.f('ix_application_deployments_status'), table_name='application_deployments')
    op.drop_index(op.f('ix_application_deployments_organization_id'), table_name='application_deployments')
    op.drop_index(op.f('ix_application_deployments_id'), table_name='application_deployments')
    op.drop_index(op.f('ix_application_deployments_environment_id'), table_name='application_deployments')
    op.drop_index(op.f('ix_application_deployments_application_release_id'), table_name='application_deployments')
    op.drop_table('application_deployments')
    op.drop_index(op.f('ix_runtime_secret_bindings_organization_id'), table_name='runtime_secret_bindings')
    op.drop_index(op.f('ix_runtime_secret_bindings_id'), table_name='runtime_secret_bindings')
    op.drop_index(op.f('ix_runtime_secret_bindings_environment_id'), table_name='runtime_secret_bindings')
    op.drop_table('runtime_secret_bindings')
    op.drop_index(op.f('ix_domain_bindings_organization_id'), table_name='domain_bindings')
    op.drop_index(op.f('ix_domain_bindings_id'), table_name='domain_bindings')
    op.drop_index(op.f('ix_domain_bindings_environment_id'), table_name='domain_bindings')
    op.drop_index(op.f('ix_domain_bindings_domain'), table_name='domain_bindings')
    op.drop_index(op.f('ix_domain_bindings_application_id'), table_name='domain_bindings')
    op.drop_table('domain_bindings')
    op.drop_index(op.f('ix_application_releases_version'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_status'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_organization_id'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_id'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_environment_id'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_commit_sha'), table_name='application_releases')
    op.drop_index(op.f('ix_application_releases_application_id'), table_name='application_releases')
    op.drop_table('application_releases')
    # ### end Alembic commands ###
