"""initial_schema_with_phase3_infrastructure

Revision ID: 91e6bf385da8
Revises: 
Create Date: 2026-10-01 16:43:11.561642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e6bf385da8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('backup_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.String(length=20), nullable=False),
    sa.Column('encryption_status', sa.String(length=50), nullable=False),
    sa.Column('rpo_minutes', sa.String(length=20), nullable=False),
    sa.Column('rto_minutes', sa.String(length=20), nullable=False),
    sa.Column('last_backup_time', sa.String(length=100), nullable=False),
    sa.Column('last_restore_test_date', sa.String(length=100), nullable=False),
    sa.Column('last_restore_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_policies_application_id'), 'backup_policies', ['application_id'], unique=False)
    op.create_index(op.f('ix_backup_policies_id'), 'backup_policies', ['id'], unique=False)
    op.create_index(op.f('ix_backup_policies_organization_id'), 'backup_policies', ['organization_id'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('role_arn', sa.String(length=500), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_accounts_id'), 'cloud_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_organization_id'), 'cloud_accounts', ['organization_id'], unique=False)
    op.create_table('compliance_assessments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('framework_code', sa.String(length=50), nullable=False),
    sa.Column('framework_name', sa.String(length=255), nullable=False),
    sa.Column('readiness_percentage', sa.String(length=10), nullable=False),
    sa.Column('passing_controls', sa.String(length=10), nullable=False),
    sa.Column('total_controls', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessments_application_id'), 'compliance_assessments', ['application_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_id'), 'compliance_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_organization_id'), 'compliance_assessments', ['organization_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('aws_monthly_budget', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('security_findings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cvss_score', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('owasp_mapping', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('suggested_fix', sa.String(length=2000), nullable=True),
    sa.Column('affected_asset', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_application_id'), 'security_findings', ['application_id'], unique=False)
    op.create_index(op.f('ix_security_findings_id'), 'security_findings', ['id'], unique=False)
    op.create_index(op.f('ix_security_findings_organization_id'), 'security_findings', ['organization_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('customer_notes', sa.String(length=1000), nullable=True),
    sa.Column('estimated_delivery', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_organization_id'), 'service_requests', ['organization_id'], unique=False)
    op.create_table('subprocessors',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('data_processed', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('dpa_status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subprocessors_id'), 'subprocessors', ['id'], unique=False)
    op.create_index(op.f('ix_subprocessors_organization_id'), 'subprocessors', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vapt_projects',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('methodology', sa.String(length=255), nullable=False),
    sa.Column('lead_tester', sa.String(length=255), nullable=False),
    sa.Column('critical_count', sa.String(length=10), nullable=False),
    sa.Column('high_count', sa.String(length=10), nullable=False),
    sa.Column('medium_count', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vapt_projects_application_id'), 'vapt_projects', ['application_id'], unique=False)
    op.create_index(op.f('ix_vapt_projects_id'), 'vapt_projects', ['id'], unique=False)
    op.create_index(op.f('ix_vapt_projects_organization_id'), 'vapt_projects', ['organization_id'], unique=False)
    op.create_table('applications',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('repo_branch', sa.String(length=100), nullable=False),
    sa.Column('repo_provider', sa.String(length=50), nullable=False),
    sa.Column('framework_frontend', sa.String(length=100), nullable=False),
    sa.Column('framework_backend', sa.String(length=100), nullable=False),
    sa.Column('database_engine', sa.String(length=100), nullable=False),
    sa.Column('runtime', sa.String(length=100), nullable=False),
    sa.Column('containerized', sa.Boolean(), nullable=False),
    sa.Column('health_endpoint', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ANALYZING', 'READY_FOR_ARCHITECTURE', 'READY_TO_DEPLOY', 'DEPLOYING', 'HEALTHY', 'DEGRADED', name='appstatus'), nullable=False),
    sa.Column('production_readiness_score', sa.String(length=10), nullable=False),
    sa.Column('security_posture_score', sa.String(length=10), nullable=False),
    sa.Column('compliance_readiness_score', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_organization_id'), 'applications', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'DEVELOPER', 'DEVOPS', 'SECURITY', 'COMPLIANCE', 'AUDITOR', 'VIEWER', name='membershiprole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_memberships_id'), 'organization_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('source_control_connections',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GITLAB', 'BITBUCKET', name='sourcecontrolprovidertype'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=100), nullable=False),
    sa.Column('provider_account_name', sa.String(length=255), nullable=False),
    sa.Column('installation_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', 'ERROR', name='connectionstatus'), nullable=False),
    sa.Column('connected_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_control_connections_id'), 'source_control_connections', ['id'], unique=False)
    op.create_index(op.f('ix_source_control_connections_installation_id'), 'source_control_connections', ['installation_id'], unique=False)
    op.create_index(op.f('ix_source_control_connections_organization_id'), 'source_control_connections', ['organization_id'], unique=False)
    op.create_table('architectures',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architectures_application_id'), 'architectures', ['application_id'], unique=False)
    op.create_index(op.f('ix_architectures_id'), 'architectures', ['id'], unique=False)
    op.create_index(op.f('ix_architectures_organization_id'), 'architectures', ['organization_id'], unique=False)
    op.create_table('deployments',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('commit_sha', sa.String(length=50), nullable=False),
    sa.Column('initiated_by', sa.String(length=255), nullable=False),
    sa.Column('logs_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_organization_id'), 'deployments', ['organization_id'], unique=False)
    op.create_table('environments',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('aws_region', sa.String(length=50), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('https_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_application_id'), 'environments', ['application_id'], unique=False)
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_organization_id'), 'environments', ['organization_id'], unique=False)
    op.create_table('repositories',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_control_connection_id', sa.String(length=36), nullable=False),
    sa.Column('provider_repository_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_control_connection_id'], ['source_control_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_repositories_provider_repository_id'), 'repositories', ['provider_repository_id'], unique=False)
    op.create_index(op.f('ix_repositories_source_control_connection_id'), 'repositories', ['source_control_connection_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'FETCHING_REPOSITORY', 'INDEXING', 'DETECTING_STACK', 'ANALYZING_SERVICES', 'ANALYZING_DEPENDENCIES', 'ANALYZING_CONFIGURATION', 'ANALYZING_SECURITY', 'GENERATING_ARCHITECTURE', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_application_id'), 'analysis_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_organization_id'), 'analysis_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_repository_id'), 'analysis_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('application_repositories',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('root_path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_repositories_application_id'), 'application_repositories', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_repositories_id'), 'application_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_application_repositories_organization_id'), 'application_repositories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_application_repositories_repository_id'), 'application_repositories', ['repository_id'], unique=False)
    op.create_table('infrastructure_stacks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('architecture_id', sa.String(length=36), nullable=True),
    sa.Column('cloud_account_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('specification_json', sa.JSON(), nullable=True),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_stacks_application_id'), 'infrastructure_stacks', ['application_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_architecture_id'), 'infrastructure_stacks', ['architecture_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_cloud_account_id'), 'infrastructure_stacks', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_environment_id'), 'infrastructure_stacks', ['environment_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_id'), 'infrastructure_stacks', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_organization_id'), 'infrastructure_stacks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_stacks_status'), 'infrastructure_stacks', ['status'], unique=False)
    op.create_table('repository_branches',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_branches_id'), 'repository_branches', ['id'], unique=False)
    op.create_index(op.f('ix_repository_branches_organization_id'), 'repository_branches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_repository_branches_repository_id'), 'repository_branches', ['repository_id'], unique=False)
    op.create_table('analysis_artifacts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_artifacts_analysis_run_id'), 'analysis_artifacts', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_artifacts_id'), 'analysis_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_artifacts_organization_id'), 'analysis_artifacts', ['organization_id'], unique=False)
    op.create_table('analysis_findings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('line_hint', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_findings_analysis_run_id'), 'analysis_findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_findings_id'), 'analysis_findings', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_findings_organization_id'), 'analysis_findings', ['organization_id'], unique=False)
    op.create_table('architecture_recommendations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('architecture_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('generator_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('estimated_monthly_cost_min', sa.Integer(), nullable=False),
    sa.Column('estimated_monthly_cost_max', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_recommendations_analysis_run_id'), 'architecture_recommendations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_architecture_recommendations_id'), 'architecture_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_architecture_recommendations_organization_id'), 'architecture_recommendations', ['organization_id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('architecture_node_id', sa.String(length=100), nullable=True),
    sa.Column('provider_resource_id', sa.String(length=255), nullable=False),
    sa.Column('provider_resource_arn', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('availability_zone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('managed_by_launchcomply', sa.String(length=50), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_resources_application_id'), 'cloud_resources', ['application_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_architecture_node_id'), 'cloud_resources', ['architecture_node_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_environment_id'), 'cloud_resources', ['environment_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_id'), 'cloud_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_infrastructure_stack_id'), 'cloud_resources', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_organization_id'), 'cloud_resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_provider_resource_id'), 'cloud_resources', ['provider_resource_id'], unique=False)
    op.create_table('detected_data_flows',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('target_service', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_data_flows_analysis_run_id'), 'detected_data_flows', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_data_flows_id'), 'detected_data_flows', ['id'], unique=False)
    op.create_index(op.f('ix_detected_data_flows_organization_id'), 'detected_data_flows', ['organization_id'], unique=False)
    op.create_table('detected_external_integrations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_external_integrations_analysis_run_id'), 'detected_external_integrations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_external_integrations_id'), 'detected_external_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_detected_external_integrations_organization_id'), 'detected_external_integrations', ['organization_id'], unique=False)
    op.create_table('detected_services',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.Enum('FRONTEND', 'BACKEND', 'WORKER', 'SCHEDULER', 'DATABASE', 'CACHE', 'QUEUE', 'STORAGE', 'PROXY', 'UNKNOWN', name='servicetype'), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('runtime', sa.String(length=100), nullable=True),
    sa.Column('runtime_version', sa.String(length=50), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=True),
    sa.Column('root_path', sa.String(length=500), nullable=False),
    sa.Column('build_command', sa.String(length=500), nullable=True),
    sa.Column('start_command', sa.String(length=500), nullable=True),
    sa.Column('containerized', sa.Boolean(), nullable=False),
    sa.Column('dockerfile_path', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_services_analysis_run_id'), 'detected_services', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_services_id'), 'detected_services', ['id'], unique=False)
    op.create_index(op.f('ix_detected_services_organization_id'), 'detected_services', ['organization_id'], unique=False)
    op.create_table('drift_detection_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drift_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_detection_runs_id'), 'drift_detection_runs', ['id'], unique=False)
    op.create_index(op.f('ix_drift_detection_runs_infrastructure_stack_id'), 'drift_detection_runs', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_drift_detection_runs_organization_id'), 'drift_detection_runs', ['organization_id'], unique=False)
    op.create_table('infrastructure_outputs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_outputs_id'), 'infrastructure_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_outputs_infrastructure_stack_id'), 'infrastructure_outputs', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_outputs_organization_id'), 'infrastructure_outputs', ['organization_id'], unique=False)
    op.create_table('infrastructure_plans',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_key', sa.String(length=255), nullable=True),
    sa.Column('plan_summary_json', sa.JSON(), nullable=True),
    sa.Column('resources_add', sa.Integer(), nullable=False),
    sa.Column('resources_change', sa.Integer(), nullable=False),
    sa.Column('resources_destroy', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_delta', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_plans_id'), 'infrastructure_plans', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_plans_infrastructure_stack_id'), 'infrastructure_plans', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_plans_organization_id'), 'infrastructure_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_plans_status'), 'infrastructure_plans', ['status'], unique=False)
    op.create_table('infrastructure_versions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('architecture_version', sa.String(length=50), nullable=False),
    sa.Column('specification_json', sa.JSON(), nullable=False),
    sa.Column('iac_engine', sa.String(length=50), nullable=False),
    sa.Column('iac_version', sa.String(length=20), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_versions_id'), 'infrastructure_versions', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_versions_infrastructure_stack_id'), 'infrastructure_versions', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_versions_organization_id'), 'infrastructure_versions', ['organization_id'], unique=False)
    op.create_table('terraform_state_references',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('backend_type', sa.String(length=50), nullable=False),
    sa.Column('state_location', sa.String(length=500), nullable=False),
    sa.Column('lock_identifier', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terraform_state_references_id'), 'terraform_state_references', ['id'], unique=False)
    op.create_index(op.f('ix_terraform_state_references_infrastructure_stack_id'), 'terraform_state_references', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_terraform_state_references_organization_id'), 'terraform_state_references', ['organization_id'], unique=False)
    op.create_table('detected_databases',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('detected_service_id', sa.String(length=36), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=True),
    sa.Column('orm', sa.String(length=100), nullable=True),
    sa.Column('connection_source', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detected_service_id'], ['detected_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_databases_analysis_run_id'), 'detected_databases', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_databases_id'), 'detected_databases', ['id'], unique=False)
    op.create_index(op.f('ix_detected_databases_organization_id'), 'detected_databases', ['organization_id'], unique=False)
    op.create_table('detected_dependencies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('detected_service_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_spec', sa.String(length=100), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('manifest_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detected_service_id'], ['detected_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_dependencies_analysis_run_id'), 'detected_dependencies', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_dependencies_id'), 'detected_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_detected_dependencies_organization_id'), 'detected_dependencies', ['organization_id'], unique=False)
    op.create_table('detected_environment_variables',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('detected_service_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('secret_likely', sa.Boolean(), nullable=False),
    sa.Column('default_present', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detected_service_id'], ['detected_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_environment_variables_analysis_run_id'), 'detected_environment_variables', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_detected_environment_variables_id'), 'detected_environment_variables', ['id'], unique=False)
    op.create_index(op.f('ix_detected_environment_variables_name'), 'detected_environment_variables', ['name'], unique=False)
    op.create_index(op.f('ix_detected_environment_variables_organization_id'), 'detected_environment_variables', ['organization_id'], unique=False)
    op.create_table('detected_health_checks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('detected_service_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detected_service_id'], ['detected_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_health_checks_detected_service_id'), 'detected_health_checks', ['detected_service_id'], unique=False)
    op.create_index(op.f('ix_detected_health_checks_id'), 'detected_health_checks', ['id'], unique=False)
    op.create_index(op.f('ix_detected_health_checks_organization_id'), 'detected_health_checks', ['organization_id'], unique=False)
    op.create_table('detected_ports',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('detected_service_id', sa.String(length=36), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('public_required', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detected_service_id'], ['detected_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_ports_detected_service_id'), 'detected_ports', ['detected_service_id'], unique=False)
    op.create_index(op.f('ix_detected_ports_id'), 'detected_ports', ['id'], unique=False)
    op.create_index(op.f('ix_detected_ports_organization_id'), 'detected_ports', ['organization_id'], unique=False)
    op.create_table('infrastructure_evidences',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('cloud_resource_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cloud_resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_evidences_cloud_resource_id'), 'infrastructure_evidences', ['cloud_resource_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_evidences_id'), 'infrastructure_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_evidences_infrastructure_stack_id'), 'infrastructure_evidences', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_evidences_organization_id'), 'infrastructure_evidences', ['organization_id'], unique=False)
    op.create_table('provisioning_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_stack_id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_plan_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('worker_job_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_plan_id'], ['infrastructure_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['infrastructure_stack_id'], ['infrastructure_stacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_runs_id'), 'provisioning_runs', ['id'], unique=False)
    op.create_index(op.f('ix_provisioning_runs_infrastructure_stack_id'), 'provisioning_runs', ['infrastructure_stack_id'], unique=False)
    op.create_index(op.f('ix_provisioning_runs_organization_id'), 'provisioning_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provisioning_runs_status'), 'provisioning_runs', ['status'], unique=False)
    op.create_table('resource_drifts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('drift_detection_run_id', sa.String(length=36), nullable=False),
    sa.Column('cloud_resource_id', sa.String(length=36), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cloud_resource_id'], ['cloud_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drift_detection_run_id'], ['drift_detection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_drifts_cloud_resource_id'), 'resource_drifts', ['cloud_resource_id'], unique=False)
    op.create_index(op.f('ix_resource_drifts_drift_detection_run_id'), 'resource_drifts', ['drift_detection_run_id'], unique=False)
    op.create_index(op.f('ix_resource_drifts_id'), 'resource_drifts', ['id'], unique=False)
    op.create_index(op.f('ix_resource_drifts_organization_id'), 'resource_drifts', ['organization_id'], unique=False)
    op.create_table('provisioning_steps',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provisioning_run_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provisioning_run_id'], ['provisioning_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_steps_id'), 'provisioning_steps', ['id'], unique=False)
    op.create_index(op.f('ix_provisioning_steps_organization_id'), 'provisioning_steps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provisioning_steps_provisioning_run_id'), 'provisioning_steps', ['provisioning_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provisioning_steps_provisioning_run_id'), table_name='provisioning_steps')
    op.drop_index(op.f('ix_provisioning_steps_organization_id'), table_name='provisioning_steps')
    op.drop_index(op.f('ix_provisioning_steps_id'), table_name='provisioning_steps')
    op.drop_table('provisioning_steps')
    op.drop_index(op.f('ix_resource_drifts_organization_id'), table_name='resource_drifts')
    op.drop_index(op.f('ix_resource_drifts_id'), table_name='resource_drifts')
    op.drop_index(op.f('ix_resource_drifts_drift_detection_run_id'), table_name='resource_drifts')
    op.drop_index(op.f('ix_resource_drifts_cloud_resource_id'), table_name='resource_drifts')
    op.drop_table('resource_drifts')
    op.drop_index(op.f('ix_provisioning_runs_status'), table_name='provisioning_runs')
    op.drop_index(op.f('ix_provisioning_runs_organization_id'), table_name='provisioning_runs')
    op.drop_index(op.f('ix_provisioning_runs_infrastructure_stack_id'), table_name='provisioning_runs')
    op.drop_index(op.f('ix_provisioning_runs_id'), table_name='provisioning_runs')
    op.drop_table('provisioning_runs')
    op.drop_index(op.f('ix_infrastructure_evidences_organization_id'), table_name='infrastructure_evidences')
    op.drop_index(op.f('ix_infrastructure_evidences_infrastructure_stack_id'), table_name='infrastructure_evidences')
    op.drop_index(op.f('ix_infrastructure_evidences_id'), table_name='infrastructure_evidences')
    op.drop_index(op.f('ix_infrastructure_evidences_cloud_resource_id'), table_name='infrastructure_evidences')
    op.drop_table('infrastructure_evidences')
    op.drop_index(op.f('ix_detected_ports_organization_id'), table_name='detected_ports')
    op.drop_index(op.f('ix_detected_ports_id'), table_name='detected_ports')
    op.drop_index(op.f('ix_detected_ports_detected_service_id'), table_name='detected_ports')
    op.drop_table('detected_ports')
    op.drop_index(op.f('ix_detected_health_checks_organization_id'), table_name='detected_health_checks')
    op.drop_index(op.f('ix_detected_health_checks_id'), table_name='detected_health_checks')
    op.drop_index(op.f('ix_detected_health_checks_detected_service_id'), table_name='detected_health_checks')
    op.drop_table('detected_health_checks')
    op.drop_index(op.f('ix_detected_environment_variables_organization_id'), table_name='detected_environment_variables')
    op.drop_index(op.f('ix_detected_environment_variables_name'), table_name='detected_environment_variables')
    op.drop_index(op.f('ix_detected_environment_variables_id'), table_name='detected_environment_variables')
    op.drop_index(op.f('ix_detected_environment_variables_analysis_run_id'), table_name='detected_environment_variables')
    op.drop_table('detected_environment_variables')
    op.drop_index(op.f('ix_detected_dependencies_organization_id'), table_name='detected_dependencies')
    op.drop_index(op.f('ix_detected_dependencies_id'), table_name='detected_dependencies')
    op.drop_index(op.f('ix_detected_dependencies_analysis_run_id'), table_name='detected_dependencies')
    op.drop_table('detected_dependencies')
    op.drop_index(op.f('ix_detected_databases_organization_id'), table_name='detected_databases')
    op.drop_index(op.f('ix_detected_databases_id'), table_name='detected_databases')
    op.drop_index(op.f('ix_detected_databases_analysis_run_id'), table_name='detected_databases')
    op.drop_table('detected_databases')
    op.drop_index(op.f('ix_terraform_state_references_organization_id'), table_name='terraform_state_references')
    op.drop_index(op.f('ix_terraform_state_references_infrastructure_stack_id'), table_name='terraform_state_references')
    op.drop_index(op.f('ix_terraform_state_references_id'), table_name='terraform_state_references')
    op.drop_table('terraform_state_references')
    op.drop_index(op.f('ix_infrastructure_versions_organization_id'), table_name='infrastructure_versions')
    op.drop_index(op.f('ix_infrastructure_versions_infrastructure_stack_id'), table_name='infrastructure_versions')
    op.drop_index(op.f('ix_infrastructure_versions_id'), table_name='infrastructure_versions')
    op.drop_table('infrastructure_versions')
    op.drop_index(op.f('ix_infrastructure_plans_status'), table_name='infrastructure_plans')
    op.drop_index(op.f('ix_infrastructure_plans_organization_id'), table_name='infrastructure_plans')
    op.drop_index(op.f('ix_infrastructure_plans_infrastructure_stack_id'), table_name='infrastructure_plans')
    op.drop_index(op.f('ix_infrastructure_plans_id'), table_name='infrastructure_plans')
    op.drop_table('infrastructure_plans')
    op.drop_index(op.f('ix_infrastructure_outputs_organization_id'), table_name='infrastructure_outputs')
    op.drop_index(op.f('ix_infrastructure_outputs_infrastructure_stack_id'), table_name='infrastructure_outputs')
    op.drop_index(op.f('ix_infrastructure_outputs_id'), table_name='infrastructure_outputs')
    op.drop_table('infrastructure_outputs')
    op.drop_index(op.f('ix_drift_detection_runs_organization_id'), table_name='drift_detection_runs')
    op.drop_index(op.f('ix_drift_detection_runs_infrastructure_stack_id'), table_name='drift_detection_runs')
    op.drop_index(op.f('ix_drift_detection_runs_id'), table_name='drift_detection_runs')
    op.drop_table('drift_detection_runs')
    op.drop_index(op.f('ix_detected_services_organization_id'), table_name='detected_services')
    op.drop_index(op.f('ix_detected_services_id'), table_name='detected_services')
    op.drop_index(op.f('ix_detected_services_analysis_run_id'), table_name='detected_services')
    op.drop_table('detected_services')
    op.drop_index(op.f('ix_detected_external_integrations_organization_id'), table_name='detected_external_integrations')
    op.drop_index(op.f('ix_detected_external_integrations_id'), table_name='detected_external_integrations')
    op.drop_index(op.f('ix_detected_external_integrations_analysis_run_id'), table_name='detected_external_integrations')
    op.drop_table('detected_external_integrations')
    op.drop_index(op.f('ix_detected_data_flows_organization_id'), table_name='detected_data_flows')
    op.drop_index(op.f('ix_detected_data_flows_id'), table_name='detected_data_flows')
    op.drop_index(op.f('ix_detected_data_flows_analysis_run_id'), table_name='detected_data_flows')
    op.drop_table('detected_data_flows')
    op.drop_index(op.f('ix_cloud_resources_provider_resource_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_organization_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_infrastructure_stack_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_environment_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_architecture_node_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_application_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_architecture_recommendations_organization_id'), table_name='architecture_recommendations')
    op.drop_index(op.f('ix_architecture_recommendations_id'), table_name='architecture_recommendations')
    op.drop_index(op.f('ix_architecture_recommendations_analysis_run_id'), table_name='architecture_recommendations')
    op.drop_table('architecture_recommendations')
    op.drop_index(op.f('ix_analysis_findings_organization_id'), table_name='analysis_findings')
    op.drop_index(op.f('ix_analysis_findings_id'), table_name='analysis_findings')
    op.drop_index(op.f('ix_analysis_findings_analysis_run_id'), table_name='analysis_findings')
    op.drop_table('analysis_findings')
    op.drop_index(op.f('ix_analysis_artifacts_organization_id'), table_name='analysis_artifacts')
    op.drop_index(op.f('ix_analysis_artifacts_id'), table_name='analysis_artifacts')
    op.drop_index(op.f('ix_analysis_artifacts_analysis_run_id'), table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    op.drop_index(op.f('ix_repository_branches_repository_id'), table_name='repository_branches')
    op.drop_index(op.f('ix_repository_branches_organization_id'), table_name='repository_branches')
    op.drop_index(op.f('ix_repository_branches_id'), table_name='repository_branches')
    op.drop_table('repository_branches')
    op.drop_index(op.f('ix_infrastructure_stacks_status'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_organization_id'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_id'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_environment_id'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_cloud_account_id'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_architecture_id'), table_name='infrastructure_stacks')
    op.drop_index(op.f('ix_infrastructure_stacks_application_id'), table_name='infrastructure_stacks')
    op.drop_table('infrastructure_stacks')
    op.drop_index(op.f('ix_application_repositories_repository_id'), table_name='application_repositories')
    op.drop_index(op.f('ix_application_repositories_organization_id'), table_name='application_repositories')
    op.drop_index(op.f('ix_application_repositories_id'), table_name='application_repositories')
    op.drop_index(op.f('ix_application_repositories_application_id'), table_name='application_repositories')
    op.drop_table('application_repositories')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_repository_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_organization_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_application_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_repositories_source_control_connection_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_provider_repository_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_environments_organization_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_application_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_deployments_organization_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_architectures_organization_id'), table_name='architectures')
    op.drop_index(op.f('ix_architectures_id'), table_name='architectures')
    op.drop_index(op.f('ix_architectures_application_id'), table_name='architectures')
    op.drop_table('architectures')
    op.drop_index(op.f('ix_source_control_connections_organization_id'), table_name='source_control_connections')
    op.drop_index(op.f('ix_source_control_connections_installation_id'), table_name='source_control_connections')
    op.drop_index(op.f('ix_source_control_connections_id'), table_name='source_control_connections')
    op.drop_table('source_control_connections')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_applications_organization_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_vapt_projects_organization_id'), table_name='vapt_projects')
    op.drop_index(op.f('ix_vapt_projects_id'), table_name='vapt_projects')
    op.drop_index(op.f('ix_vapt_projects_application_id'), table_name='vapt_projects')
    op.drop_table('vapt_projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subprocessors_organization_id'), table_name='subprocessors')
    op.drop_index(op.f('ix_subprocessors_id'), table_name='subprocessors')
    op.drop_table('subprocessors')
    op.drop_index(op.f('ix_service_requests_organization_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_security_findings_organization_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_application_id'), table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_compliance_assessments_organization_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_application_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_index(op.f('ix_cloud_accounts_organization_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_backup_policies_organization_id'), table_name='backup_policies')
    op.drop_index(op.f('ix_backup_policies_id'), table_name='backup_policies')
    op.drop_index(op.f('ix_backup_policies_application_id'), table_name='backup_policies')
    op.drop_table('backup_policies')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
