"""phase6_security_assurance_vapt_dr_auditor

Revision ID: a375b8149d14
Revises: d405af46acb7
Create Date: 2026-10-01 22:44:50.749178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a375b8149d14'
down_revision: Union[str, Sequence[str], None] = 'd405af46acb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extend the existing findings table rather than recreating prior schema.
    with op.batch_alter_table('security_findings') as batch_op:
        batch_op.alter_column('description', existing_type=sa.String(1000), type_=sa.String(2000), existing_nullable=False)
        batch_op.alter_column('suggested_fix', existing_type=sa.String(2000), type_=sa.String(4000), existing_nullable=True)
        batch_op.add_column(sa.Column('environment_id', sa.String(36), nullable=True))
        batch_op.add_column(sa.Column('assessment_id', sa.String(36), nullable=True))
        batch_op.add_column(sa.Column('cvss_vector', sa.String(100), nullable=True))
        batch_op.add_column(sa.Column('cwe', sa.String(50), nullable=True))
        batch_op.add_column(sa.Column('scanner', sa.String(50), nullable=False, server_default='LEGACY'))
        batch_op.add_column(sa.Column('finding_type', sa.String(100), nullable=False, server_default='VULNERABILITY'))
        batch_op.add_column(sa.Column('endpoint', sa.String(500), nullable=True))
        batch_op.add_column(sa.Column('file', sa.String(500), nullable=True))
        batch_op.add_column(sa.Column('line', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(20), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('business_impact', sa.String(1000), nullable=True))
        batch_op.add_column(sa.Column('technical_impact', sa.String(1000), nullable=True))
        batch_op.add_column(sa.Column('remediation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('detected_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retest_status', sa.String(50), nullable=False, server_default='NONE'))
        batch_op.add_column(sa.Column('sla_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fingerprint', sa.String(64), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor_access_grants',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('auditor_email', sa.String(length=255), nullable=False),
    sa.Column('auditor_name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_access_grants_auditor_email'), 'auditor_access_grants', ['auditor_email'], unique=False)
    op.create_index(op.f('ix_auditor_access_grants_id'), 'auditor_access_grants', ['id'], unique=False)
    op.create_index(op.f('ix_auditor_access_grants_organization_id'), 'auditor_access_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auditor_access_grants_status'), 'auditor_access_grants', ['status'], unique=False)
    op.create_table('disaster_recovery_plans',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_region', sa.String(length=50), nullable=False),
    sa.Column('secondary_region', sa.String(length=50), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('target_rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('target_rto_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('replication_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_recovery_plans_application_id'), 'disaster_recovery_plans', ['application_id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_plans_environment_id'), 'disaster_recovery_plans', ['environment_id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_plans_id'), 'disaster_recovery_plans', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_plans_organization_id'), 'disaster_recovery_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_plans_status'), 'disaster_recovery_plans', ['status'], unique=False)
    op.create_table('remediation_pull_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_pull_requests_finding_id'), 'remediation_pull_requests', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_pull_requests_id'), 'remediation_pull_requests', ['id'], unique=False)
    op.create_index(op.f('ix_remediation_pull_requests_organization_id'), 'remediation_pull_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_remediation_pull_requests_status'), 'remediation_pull_requests', ['status'], unique=False)
    op.create_table('security_assessment_scopes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('testing_start', sa.DateTime(), nullable=True),
    sa.Column('testing_end', sa.DateTime(), nullable=True),
    sa.Column('rules_of_engagement', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_assessment_scopes_application_id'), 'security_assessment_scopes', ['application_id'], unique=False)
    op.create_index(op.f('ix_security_assessment_scopes_environment_id'), 'security_assessment_scopes', ['environment_id'], unique=False)
    op.create_index(op.f('ix_security_assessment_scopes_id'), 'security_assessment_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_security_assessment_scopes_organization_id'), 'security_assessment_scopes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_assessment_scopes_status'), 'security_assessment_scopes', ['status'], unique=False)
    op.create_index(op.f('ix_security_findings_assessment_id'), 'security_findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_security_findings_environment_id'), 'security_findings', ['environment_id'], unique=False)
    op.create_index(op.f('ix_security_findings_fingerprint'), 'security_findings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_security_findings_status'), 'security_findings', ['status'], unique=False)
    op.create_table('security_questionnaires',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_questionnaires_id'), 'security_questionnaires', ['id'], unique=False)
    op.create_index(op.f('ix_security_questionnaires_organization_id'), 'security_questionnaires', ['organization_id'], unique=False)
    op.create_table('security_risk_acceptances',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('compensating_control', sa.Text(), nullable=False),
    sa.Column('accepted_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_risk_acceptances_finding_id'), 'security_risk_acceptances', ['finding_id'], unique=False)
    op.create_index(op.f('ix_security_risk_acceptances_id'), 'security_risk_acceptances', ['id'], unique=False)
    op.create_index(op.f('ix_security_risk_acceptances_organization_id'), 'security_risk_acceptances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_risk_acceptances_status'), 'security_risk_acceptances', ['status'], unique=False)
    op.create_table('trust_center_profiles',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('public_enabled', sa.Boolean(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('security_contact_email', sa.String(length=255), nullable=False),
    sa.Column('overview_markdown', sa.Text(), nullable=True),
    sa.Column('encryption_summary', sa.String(length=500), nullable=True),
    sa.Column('backup_summary', sa.String(length=500), nullable=True),
    sa.Column('compliance_status_json', sa.JSON(), nullable=False),
    sa.Column('nda_required_documents_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_center_profiles_id'), 'trust_center_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_trust_center_profiles_organization_id'), 'trust_center_profiles', ['organization_id'], unique=True)
    op.create_table('auditor_evidence_requests',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('request_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('provided_evidence_id', sa.String(length=255), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['auditor_access_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_evidence_requests_grant_id'), 'auditor_evidence_requests', ['grant_id'], unique=False)
    op.create_index(op.f('ix_auditor_evidence_requests_id'), 'auditor_evidence_requests', ['id'], unique=False)
    op.create_index(op.f('ix_auditor_evidence_requests_organization_id'), 'auditor_evidence_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auditor_evidence_requests_status'), 'auditor_evidence_requests', ['status'], unique=False)
    op.create_table('disaster_recovery_drills',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dr_plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('observed_rto_seconds', sa.Float(), nullable=True),
    sa.Column('observed_rpo_minutes', sa.Float(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('temp_resource_ids_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dr_plan_id'], ['disaster_recovery_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_recovery_drills_dr_plan_id'), 'disaster_recovery_drills', ['dr_plan_id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_drills_id'), 'disaster_recovery_drills', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_drills_organization_id'), 'disaster_recovery_drills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_disaster_recovery_drills_status'), 'disaster_recovery_drills', ['status'], unique=False)
    op.create_table('security_assessments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['security_assessment_scopes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_assessments_application_id'), 'security_assessments', ['application_id'], unique=False)
    op.create_index(op.f('ix_security_assessments_environment_id'), 'security_assessments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_security_assessments_id'), 'security_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_security_assessments_organization_id'), 'security_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_assessments_scope_id'), 'security_assessments', ['scope_id'], unique=False)
    op.create_index(op.f('ix_security_assessments_status'), 'security_assessments', ['status'], unique=False)
    op.create_table('security_assets',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_value', sa.String(length=500), nullable=False),
    sa.Column('ownership_status', sa.String(length=50), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['security_assessment_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_assets_id'), 'security_assets', ['id'], unique=False)
    op.create_index(op.f('ix_security_assets_organization_id'), 'security_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_assets_scope_id'), 'security_assets', ['scope_id'], unique=False)
    op.create_table('security_authorizations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('authorized_by', sa.String(length=255), nullable=False),
    sa.Column('authorized_role', sa.String(length=50), nullable=False),
    sa.Column('authorization_text', sa.Text(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['security_assessment_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_authorizations_id'), 'security_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_security_authorizations_organization_id'), 'security_authorizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_authorizations_scope_id'), 'security_authorizations', ['scope_id'], unique=False)
    op.create_table('security_exclusions',
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('asset', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['security_assessment_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_exclusions_id'), 'security_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_security_exclusions_scope_id'), 'security_exclusions', ['scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_exclusions_scope_id'), table_name='security_exclusions')
    op.drop_index(op.f('ix_security_exclusions_id'), table_name='security_exclusions')
    op.drop_table('security_exclusions')
    op.drop_index(op.f('ix_security_authorizations_scope_id'), table_name='security_authorizations')
    op.drop_index(op.f('ix_security_authorizations_organization_id'), table_name='security_authorizations')
    op.drop_index(op.f('ix_security_authorizations_id'), table_name='security_authorizations')
    op.drop_table('security_authorizations')
    op.drop_index(op.f('ix_security_assets_scope_id'), table_name='security_assets')
    op.drop_index(op.f('ix_security_assets_organization_id'), table_name='security_assets')
    op.drop_index(op.f('ix_security_assets_id'), table_name='security_assets')
    op.drop_table('security_assets')
    op.drop_index(op.f('ix_security_assessments_status'), table_name='security_assessments')
    op.drop_index(op.f('ix_security_assessments_scope_id'), table_name='security_assessments')
    op.drop_index(op.f('ix_security_assessments_organization_id'), table_name='security_assessments')
    op.drop_index(op.f('ix_security_assessments_id'), table_name='security_assessments')
    op.drop_index(op.f('ix_security_assessments_environment_id'), table_name='security_assessments')
    op.drop_index(op.f('ix_security_assessments_application_id'), table_name='security_assessments')
    op.drop_table('security_assessments')
    op.drop_index(op.f('ix_disaster_recovery_drills_status'), table_name='disaster_recovery_drills')
    op.drop_index(op.f('ix_disaster_recovery_drills_organization_id'), table_name='disaster_recovery_drills')
    op.drop_index(op.f('ix_disaster_recovery_drills_id'), table_name='disaster_recovery_drills')
    op.drop_index(op.f('ix_disaster_recovery_drills_dr_plan_id'), table_name='disaster_recovery_drills')
    op.drop_table('disaster_recovery_drills')
    op.drop_index(op.f('ix_auditor_evidence_requests_status'), table_name='auditor_evidence_requests')
    op.drop_index(op.f('ix_auditor_evidence_requests_organization_id'), table_name='auditor_evidence_requests')
    op.drop_index(op.f('ix_auditor_evidence_requests_id'), table_name='auditor_evidence_requests')
    op.drop_index(op.f('ix_auditor_evidence_requests_grant_id'), table_name='auditor_evidence_requests')
    op.drop_table('auditor_evidence_requests')
    op.drop_index(op.f('ix_trust_center_profiles_organization_id'), table_name='trust_center_profiles')
    op.drop_index(op.f('ix_trust_center_profiles_id'), table_name='trust_center_profiles')
    op.drop_table('trust_center_profiles')
    op.drop_index(op.f('ix_security_risk_acceptances_status'), table_name='security_risk_acceptances')
    op.drop_index(op.f('ix_security_risk_acceptances_organization_id'), table_name='security_risk_acceptances')
    op.drop_index(op.f('ix_security_risk_acceptances_id'), table_name='security_risk_acceptances')
    op.drop_index(op.f('ix_security_risk_acceptances_finding_id'), table_name='security_risk_acceptances')
    op.drop_table('security_risk_acceptances')
    op.drop_index(op.f('ix_security_questionnaires_organization_id'), table_name='security_questionnaires')
    op.drop_index(op.f('ix_security_questionnaires_id'), table_name='security_questionnaires')
    op.drop_table('security_questionnaires')
    op.drop_index(op.f('ix_security_findings_status'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_fingerprint'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_environment_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_assessment_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_assessment_scopes_status'), table_name='security_assessment_scopes')
    op.drop_index(op.f('ix_security_assessment_scopes_organization_id'), table_name='security_assessment_scopes')
    op.drop_index(op.f('ix_security_assessment_scopes_id'), table_name='security_assessment_scopes')
    op.drop_index(op.f('ix_security_assessment_scopes_environment_id'), table_name='security_assessment_scopes')
    op.drop_index(op.f('ix_security_assessment_scopes_application_id'), table_name='security_assessment_scopes')
    op.drop_table('security_assessment_scopes')
    op.drop_index(op.f('ix_remediation_pull_requests_status'), table_name='remediation_pull_requests')
    op.drop_index(op.f('ix_remediation_pull_requests_organization_id'), table_name='remediation_pull_requests')
    op.drop_index(op.f('ix_remediation_pull_requests_id'), table_name='remediation_pull_requests')
    op.drop_index(op.f('ix_remediation_pull_requests_finding_id'), table_name='remediation_pull_requests')
    op.drop_table('remediation_pull_requests')
    op.drop_index(op.f('ix_disaster_recovery_plans_status'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_disaster_recovery_plans_organization_id'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_disaster_recovery_plans_id'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_disaster_recovery_plans_environment_id'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_disaster_recovery_plans_application_id'), table_name='disaster_recovery_plans')
    op.drop_table('disaster_recovery_plans')
    op.drop_index(op.f('ix_auditor_access_grants_status'), table_name='auditor_access_grants')
    op.drop_index(op.f('ix_auditor_access_grants_organization_id'), table_name='auditor_access_grants')
    op.drop_index(op.f('ix_auditor_access_grants_id'), table_name='auditor_access_grants')
    op.drop_index(op.f('ix_auditor_access_grants_auditor_email'), table_name='auditor_access_grants')
    op.drop_table('auditor_access_grants')
    # ### end Alembic commands ###
