"""phase10_enterprise_identity_copilot_threats_partners

Revision ID: b65aff726dc6
Revises: 5dd2bef950f7
Create Date: 2026-10-03 22:01:15.296016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.migration_types import enum_type


# revision identifiers, used by Alembic.
revision: str = 'b65aff726dc6'
down_revision: Union[str, Sequence[str], None] = '5dd2bef950f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('branding_logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('primary_accent_color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_organizations_id'), 'partner_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_partner_organizations_slug'), 'partner_organizations', ['slug'], unique=True)
    op.create_table('copilot_approved_security_answers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('question_pattern', sa.String(length=500), nullable=False),
    sa.Column('approved_answer', sa.Text(), nullable=False),
    sa.Column('evidence_references_json', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_approved_security_answers_id'), 'copilot_approved_security_answers', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_approved_security_answers_organization_id'), 'copilot_approved_security_answers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_copilot_approved_security_answers_question_pattern'), 'copilot_approved_security_answers', ['question_pattern'], unique=False)
    op.create_table('copilot_conversations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', enum_type('SECURITY', 'COMPLIANCE', 'CLOUD', 'VAPT', 'INCIDENT', 'AUDIT', 'EXECUTIVE', name='copilotmode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversations_id'), 'copilot_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_mode'), 'copilot_conversations', ['mode'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_organization_id'), 'copilot_conversations', ['organization_id'], unique=False)
    op.create_table('copilot_questionnaire_uploads',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_questionnaire_uploads_id'), 'copilot_questionnaire_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_questionnaire_uploads_organization_id'), 'copilot_questionnaire_uploads', ['organization_id'], unique=False)
    op.create_table('enterprise_access_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('require_sso', sa.Boolean(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('allowed_email_domains_json', sa.Text(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_idle_minutes', sa.Integer(), nullable=False),
    sa.Column('approved_ip_ranges_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_access_policies_id'), 'enterprise_access_policies', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_access_policies_organization_id'), 'enterprise_access_policies', ['organization_id'], unique=True)
    op.create_table('enterprise_business_units',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('parent_business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_business_unit_id'], ['enterprise_business_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_business_units_id'), 'enterprise_business_units', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_business_units_organization_id'), 'enterprise_business_units', ['organization_id'], unique=False)
    op.create_table('enterprise_directory_sync_runs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('users_synced', sa.Integer(), nullable=False),
    sa.Column('groups_synced', sa.Integer(), nullable=False),
    sa.Column('users_deprovisioned', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_directory_sync_runs_id'), 'enterprise_directory_sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_directory_sync_runs_organization_id'), 'enterprise_directory_sync_runs', ['organization_id'], unique=False)
    op.create_table('enterprise_group_role_mappings',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('idp_group_name', sa.String(length=255), nullable=False),
    sa.Column('mapped_role', enum_type('OWNER', 'ADMIN', 'DEVELOPER', 'DEVOPS', 'SECURITY', 'COMPLIANCE', 'AUDITOR', 'BILLING', 'CONSULTANT', 'VIEWER', name='membershiprole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_group_role_mappings_id'), 'enterprise_group_role_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_group_role_mappings_organization_id'), 'enterprise_group_role_mappings', ['organization_id'], unique=False)
    op.create_table('enterprise_outbound_webhooks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('secret_token_encrypted', sa.Text(), nullable=False),
    sa.Column('subscribed_events_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_outbound_webhooks_id'), 'enterprise_outbound_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_outbound_webhooks_organization_id'), 'enterprise_outbound_webhooks', ['organization_id'], unique=False)
    op.create_table('enterprise_scim_configurations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_url', sa.String(length=255), nullable=False),
    sa.Column('bearer_token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_scim_configurations_id'), 'enterprise_scim_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_scim_configurations_organization_id'), 'enterprise_scim_configurations', ['organization_id'], unique=True)
    op.create_table('enterprise_service_accounts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_service_accounts_id'), 'enterprise_service_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_service_accounts_organization_id'), 'enterprise_service_accounts', ['organization_id'], unique=False)
    op.create_table('enterprise_sso_configurations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', enum_type('SAML', 'OIDC', name='ssoprovidertype'), nullable=False),
    sa.Column('sso_mode', enum_type('OPTIONAL', 'REQUIRED', 'REQUIRED_EXCEPT_BREAK_GLASS', name='ssomode'), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('acs_url', sa.String(length=255), nullable=False),
    sa.Column('idp_sso_url', sa.String(length=500), nullable=False),
    sa.Column('idp_issuer', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('jwks_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('test_login_succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_sso_configurations_id'), 'enterprise_sso_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_sso_configurations_organization_id'), 'enterprise_sso_configurations', ['organization_id'], unique=True)
    op.create_table('enterprise_verified_domains',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.Column('verification_method', enum_type('DNS_TXT', 'EMAIL', 'MANUAL', name='domainverificationmethod'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_verified_domains_domain'), 'enterprise_verified_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_enterprise_verified_domains_id'), 'enterprise_verified_domains', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_verified_domains_organization_id'), 'enterprise_verified_domains', ['organization_id'], unique=False)
    op.create_table('partner_managed_customer_relationships',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('customer_organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', enum_type('INVITED', 'PENDING_CUSTOMER_APPROVAL', 'ACTIVE', 'SUSPENDED', 'REVOKED', name='relationshipstatus'), nullable=False),
    sa.Column('delegated_permissions_json', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_managed_customer_relationships_customer_organization_id'), 'partner_managed_customer_relationships', ['customer_organization_id'], unique=False)
    op.create_index(op.f('ix_partner_managed_customer_relationships_id'), 'partner_managed_customer_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_partner_managed_customer_relationships_partner_id'), 'partner_managed_customer_relationships', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_managed_customer_relationships_status'), 'partner_managed_customer_relationships', ['status'], unique=False)
    op.create_table('partner_memberships',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', enum_type('PARTNER_ADMIN', 'PARTNER_CONSULTANT', 'PARTNER_AUDITOR', name='partnerrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_memberships_id'), 'partner_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_partner_memberships_partner_id'), 'partner_memberships', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_memberships_user_id'), 'partner_memberships', ['user_id'], unique=False)
    op.create_table('partner_service_catalogs',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_service_catalogs_id'), 'partner_service_catalogs', ['id'], unique=False)
    op.create_index(op.f('ix_partner_service_catalogs_partner_id'), 'partner_service_catalogs', ['partner_id'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', enum_type('SUPPORTED', 'PARTIALLY_SUPPORTED', 'INSUFFICIENT_EVIDENCE', name='copilotconfidence'), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_id'), 'copilot_messages', ['id'], unique=False)
    op.create_table('copilot_questionnaire_items',
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('status', enum_type('UNANSWERED', 'AI_DRAFTED', 'HUMAN_REVIEW', 'APPROVED', 'NEEDS_EVIDENCE', 'REJECTED', name='questionnaireitemstatus'), nullable=False),
    sa.Column('confidence', enum_type('SUPPORTED', 'PARTIALLY_SUPPORTED', 'INSUFFICIENT_EVIDENCE', name='copilotconfidence'), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['copilot_questionnaire_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_questionnaire_items_id'), 'copilot_questionnaire_items', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_questionnaire_items_questionnaire_id'), 'copilot_questionnaire_items', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_copilot_questionnaire_items_status'), 'copilot_questionnaire_items', ['status'], unique=False)
    op.create_table('enterprise_business_unit_memberships',
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', enum_type('BU_ADMIN', 'REGIONAL_ADMIN', 'BU_MEMBER', name='businessunitrole'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['enterprise_business_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_business_unit_memberships_business_unit_id'), 'enterprise_business_unit_memberships', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_enterprise_business_unit_memberships_id'), 'enterprise_business_unit_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_business_unit_memberships_user_id'), 'enterprise_business_unit_memberships', ['user_id'], unique=False)
    op.create_table('enterprise_custom_frameworks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('framework_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('controls_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['enterprise_business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_custom_frameworks_id'), 'enterprise_custom_frameworks', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_custom_frameworks_organization_id'), 'enterprise_custom_frameworks', ['organization_id'], unique=False)
    op.create_table('enterprise_service_account_tokens',
    sa.Column('service_account_id', sa.String(length=36), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['enterprise_service_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_service_account_tokens_id'), 'enterprise_service_account_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_service_account_tokens_service_account_id'), 'enterprise_service_account_tokens', ['service_account_id'], unique=False)
    op.create_index(op.f('ix_enterprise_service_account_tokens_token_hash'), 'enterprise_service_account_tokens', ['token_hash'], unique=True)
    op.create_table('enterprise_sso_certificates',
    sa.Column('sso_configuration_id', sa.String(length=36), nullable=False),
    sa.Column('certificate_data', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', enum_type('ACTIVE', 'NEXT', 'EXPIRED', name='certstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sso_configuration_id'], ['enterprise_sso_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_sso_certificates_id'), 'enterprise_sso_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_sso_certificates_sso_configuration_id'), 'enterprise_sso_certificates', ['sso_configuration_id'], unique=False)
    op.create_table('enterprise_webhook_deliveries',
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', enum_type('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', 'DEAD_LETTER', name='webhookdeliverystatus'), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['enterprise_outbound_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_webhook_deliveries_event_type'), 'enterprise_webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_enterprise_webhook_deliveries_id'), 'enterprise_webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_webhook_deliveries_status'), 'enterprise_webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_enterprise_webhook_deliveries_webhook_id'), 'enterprise_webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('threat_models',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_models_application_id'), 'threat_models', ['application_id'], unique=False)
    op.create_index(op.f('ix_threat_models_id'), 'threat_models', ['id'], unique=False)
    op.create_index(op.f('ix_threat_models_organization_id'), 'threat_models', ['organization_id'], unique=False)
    op.create_table('copilot_action_proposals',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', enum_type('CREATE_TASK', 'CREATE_RISK', 'DRAFT_POLICY', 'GENERATE_REMEDIATION_PR', 'DRAFT_AUDITOR_RESPONSE', name='actionproposaltype'), nullable=False),
    sa.Column('proposed_payload_json', sa.Text(), nullable=False),
    sa.Column('status', enum_type('PROPOSED', 'APPROVED', 'REJECTED', 'EXECUTED', name='actionproposalstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['copilot_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_action_proposals_id'), 'copilot_action_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_action_proposals_message_id'), 'copilot_action_proposals', ['message_id'], unique=False)
    op.create_index(op.f('ix_copilot_action_proposals_status'), 'copilot_action_proposals', ['status'], unique=False)
    op.create_table('copilot_evidence_references',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['copilot_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_evidence_references_entity_id'), 'copilot_evidence_references', ['entity_id'], unique=False)
    op.create_index(op.f('ix_copilot_evidence_references_id'), 'copilot_evidence_references', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_evidence_references_message_id'), 'copilot_evidence_references', ['message_id'], unique=False)
    op.create_table('threat_model_versions',
    sa.Column('threat_model_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('architecture_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_model_id'], ['threat_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_model_versions_id'), 'threat_model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_threat_model_versions_threat_model_id'), 'threat_model_versions', ['threat_model_id'], unique=False)
    op.create_table('threat_assets',
    sa.Column('threat_model_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('criticality', enum_type('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='threatcriticality'), nullable=False),
    sa.Column('trust_zone', sa.String(length=100), nullable=False),
    sa.Column('internet_exposed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_model_version_id'], ['threat_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_assets_id'), 'threat_assets', ['id'], unique=False)
    op.create_index(op.f('ix_threat_assets_threat_model_version_id'), 'threat_assets', ['threat_model_version_id'], unique=False)
    op.create_table('threat_attack_paths',
    sa.Column('threat_model_version_id', sa.String(length=36), nullable=False),
    sa.Column('threat_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('status', enum_type('THEORETICAL', 'POSSIBLE', 'VALIDATED', 'MITIGATED', name='attackpathstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_model_version_id'], ['threat_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_attack_paths_id'), 'threat_attack_paths', ['id'], unique=False)
    op.create_index(op.f('ix_threat_attack_paths_threat_id'), 'threat_attack_paths', ['threat_id'], unique=False)
    op.create_index(op.f('ix_threat_attack_paths_threat_model_version_id'), 'threat_attack_paths', ['threat_model_version_id'], unique=False)
    op.create_table('threat_identified_threats',
    sa.Column('threat_model_version_id', sa.String(length=36), nullable=False),
    sa.Column('threat_id', sa.String(length=50), nullable=False),
    sa.Column('category', enum_type('SPOOFING', 'TAMPERING', 'REPUDIATION', 'INFORMATION_DISCLOSURE', 'DENIAL_OF_SERVICE', 'ELEVATION_OF_PRIVILEGE', name='threatcategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entry_point', sa.String(length=255), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('risk_level', enum_type('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='threatcriticality'), nullable=False),
    sa.Column('status', enum_type('IDENTIFIED', 'MITIGATED', 'ACCEPTED', 'CLOSED', name='threatstatus'), nullable=False),
    sa.Column('risk_register_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_model_version_id'], ['threat_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_identified_threats_category'), 'threat_identified_threats', ['category'], unique=False)
    op.create_index(op.f('ix_threat_identified_threats_id'), 'threat_identified_threats', ['id'], unique=False)
    op.create_index(op.f('ix_threat_identified_threats_status'), 'threat_identified_threats', ['status'], unique=False)
    op.create_index(op.f('ix_threat_identified_threats_threat_id'), 'threat_identified_threats', ['threat_id'], unique=False)
    op.create_index(op.f('ix_threat_identified_threats_threat_model_version_id'), 'threat_identified_threats', ['threat_model_version_id'], unique=False)
    op.create_table('threat_trust_boundaries',
    sa.Column('threat_model_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('boundary_type', enum_type('INTERNET', 'EDGE', 'PUBLIC_SUBNET', 'PRIVATE_APP', 'DATABASE_SUBNET', 'THIRD_PARTY', 'ADMIN_PLANE', name='trustboundarytype'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_model_version_id'], ['threat_model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_trust_boundaries_id'), 'threat_trust_boundaries', ['id'], unique=False)
    op.create_index(op.f('ix_threat_trust_boundaries_threat_model_version_id'), 'threat_trust_boundaries', ['threat_model_version_id'], unique=False)
    op.create_table('threat_mitigations',
    sa.Column('threat_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('mitigation_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_id'], ['threat_identified_threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_mitigations_id'), 'threat_mitigations', ['id'], unique=False)
    op.create_index(op.f('ix_threat_mitigations_threat_id'), 'threat_mitigations', ['threat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_mitigations_threat_id'), table_name='threat_mitigations')
    op.drop_index(op.f('ix_threat_mitigations_id'), table_name='threat_mitigations')
    op.drop_table('threat_mitigations')
    op.drop_index(op.f('ix_threat_trust_boundaries_threat_model_version_id'), table_name='threat_trust_boundaries')
    op.drop_index(op.f('ix_threat_trust_boundaries_id'), table_name='threat_trust_boundaries')
    op.drop_table('threat_trust_boundaries')
    op.drop_index(op.f('ix_threat_identified_threats_threat_model_version_id'), table_name='threat_identified_threats')
    op.drop_index(op.f('ix_threat_identified_threats_threat_id'), table_name='threat_identified_threats')
    op.drop_index(op.f('ix_threat_identified_threats_status'), table_name='threat_identified_threats')
    op.drop_index(op.f('ix_threat_identified_threats_id'), table_name='threat_identified_threats')
    op.drop_index(op.f('ix_threat_identified_threats_category'), table_name='threat_identified_threats')
    op.drop_table('threat_identified_threats')
    op.drop_index(op.f('ix_threat_attack_paths_threat_model_version_id'), table_name='threat_attack_paths')
    op.drop_index(op.f('ix_threat_attack_paths_threat_id'), table_name='threat_attack_paths')
    op.drop_index(op.f('ix_threat_attack_paths_id'), table_name='threat_attack_paths')
    op.drop_table('threat_attack_paths')
    op.drop_index(op.f('ix_threat_assets_threat_model_version_id'), table_name='threat_assets')
    op.drop_index(op.f('ix_threat_assets_id'), table_name='threat_assets')
    op.drop_table('threat_assets')
    op.drop_index(op.f('ix_threat_model_versions_threat_model_id'), table_name='threat_model_versions')
    op.drop_index(op.f('ix_threat_model_versions_id'), table_name='threat_model_versions')
    op.drop_table('threat_model_versions')
    op.drop_index(op.f('ix_copilot_evidence_references_message_id'), table_name='copilot_evidence_references')
    op.drop_index(op.f('ix_copilot_evidence_references_id'), table_name='copilot_evidence_references')
    op.drop_index(op.f('ix_copilot_evidence_references_entity_id'), table_name='copilot_evidence_references')
    op.drop_table('copilot_evidence_references')
    op.drop_index(op.f('ix_copilot_action_proposals_status'), table_name='copilot_action_proposals')
    op.drop_index(op.f('ix_copilot_action_proposals_message_id'), table_name='copilot_action_proposals')
    op.drop_index(op.f('ix_copilot_action_proposals_id'), table_name='copilot_action_proposals')
    op.drop_table('copilot_action_proposals')
    op.drop_index(op.f('ix_threat_models_organization_id'), table_name='threat_models')
    op.drop_index(op.f('ix_threat_models_id'), table_name='threat_models')
    op.drop_index(op.f('ix_threat_models_application_id'), table_name='threat_models')
    op.drop_table('threat_models')
    op.drop_index(op.f('ix_enterprise_webhook_deliveries_webhook_id'), table_name='enterprise_webhook_deliveries')
    op.drop_index(op.f('ix_enterprise_webhook_deliveries_status'), table_name='enterprise_webhook_deliveries')
    op.drop_index(op.f('ix_enterprise_webhook_deliveries_id'), table_name='enterprise_webhook_deliveries')
    op.drop_index(op.f('ix_enterprise_webhook_deliveries_event_type'), table_name='enterprise_webhook_deliveries')
    op.drop_table('enterprise_webhook_deliveries')
    op.drop_index(op.f('ix_enterprise_sso_certificates_sso_configuration_id'), table_name='enterprise_sso_certificates')
    op.drop_index(op.f('ix_enterprise_sso_certificates_id'), table_name='enterprise_sso_certificates')
    op.drop_table('enterprise_sso_certificates')
    op.drop_index(op.f('ix_enterprise_service_account_tokens_token_hash'), table_name='enterprise_service_account_tokens')
    op.drop_index(op.f('ix_enterprise_service_account_tokens_service_account_id'), table_name='enterprise_service_account_tokens')
    op.drop_index(op.f('ix_enterprise_service_account_tokens_id'), table_name='enterprise_service_account_tokens')
    op.drop_table('enterprise_service_account_tokens')
    op.drop_index(op.f('ix_enterprise_custom_frameworks_organization_id'), table_name='enterprise_custom_frameworks')
    op.drop_index(op.f('ix_enterprise_custom_frameworks_id'), table_name='enterprise_custom_frameworks')
    op.drop_table('enterprise_custom_frameworks')
    op.drop_index(op.f('ix_enterprise_business_unit_memberships_user_id'), table_name='enterprise_business_unit_memberships')
    op.drop_index(op.f('ix_enterprise_business_unit_memberships_id'), table_name='enterprise_business_unit_memberships')
    op.drop_index(op.f('ix_enterprise_business_unit_memberships_business_unit_id'), table_name='enterprise_business_unit_memberships')
    op.drop_table('enterprise_business_unit_memberships')
    op.drop_index(op.f('ix_copilot_questionnaire_items_status'), table_name='copilot_questionnaire_items')
    op.drop_index(op.f('ix_copilot_questionnaire_items_questionnaire_id'), table_name='copilot_questionnaire_items')
    op.drop_index(op.f('ix_copilot_questionnaire_items_id'), table_name='copilot_questionnaire_items')
    op.drop_table('copilot_questionnaire_items')
    op.drop_index(op.f('ix_copilot_messages_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_partner_service_catalogs_partner_id'), table_name='partner_service_catalogs')
    op.drop_index(op.f('ix_partner_service_catalogs_id'), table_name='partner_service_catalogs')
    op.drop_table('partner_service_catalogs')
    op.drop_index(op.f('ix_partner_memberships_user_id'), table_name='partner_memberships')
    op.drop_index(op.f('ix_partner_memberships_partner_id'), table_name='partner_memberships')
    op.drop_index(op.f('ix_partner_memberships_id'), table_name='partner_memberships')
    op.drop_table('partner_memberships')
    op.drop_index(op.f('ix_partner_managed_customer_relationships_status'), table_name='partner_managed_customer_relationships')
    op.drop_index(op.f('ix_partner_managed_customer_relationships_partner_id'), table_name='partner_managed_customer_relationships')
    op.drop_index(op.f('ix_partner_managed_customer_relationships_id'), table_name='partner_managed_customer_relationships')
    op.drop_index(op.f('ix_partner_managed_customer_relationships_customer_organization_id'), table_name='partner_managed_customer_relationships')
    op.drop_table('partner_managed_customer_relationships')
    op.drop_index(op.f('ix_enterprise_verified_domains_organization_id'), table_name='enterprise_verified_domains')
    op.drop_index(op.f('ix_enterprise_verified_domains_id'), table_name='enterprise_verified_domains')
    op.drop_index(op.f('ix_enterprise_verified_domains_domain'), table_name='enterprise_verified_domains')
    op.drop_table('enterprise_verified_domains')
    op.drop_index(op.f('ix_enterprise_sso_configurations_organization_id'), table_name='enterprise_sso_configurations')
    op.drop_index(op.f('ix_enterprise_sso_configurations_id'), table_name='enterprise_sso_configurations')
    op.drop_table('enterprise_sso_configurations')
    op.drop_index(op.f('ix_enterprise_service_accounts_organization_id'), table_name='enterprise_service_accounts')
    op.drop_index(op.f('ix_enterprise_service_accounts_id'), table_name='enterprise_service_accounts')
    op.drop_table('enterprise_service_accounts')
    op.drop_index(op.f('ix_enterprise_scim_configurations_organization_id'), table_name='enterprise_scim_configurations')
    op.drop_index(op.f('ix_enterprise_scim_configurations_id'), table_name='enterprise_scim_configurations')
    op.drop_table('enterprise_scim_configurations')
    op.drop_index(op.f('ix_enterprise_outbound_webhooks_organization_id'), table_name='enterprise_outbound_webhooks')
    op.drop_index(op.f('ix_enterprise_outbound_webhooks_id'), table_name='enterprise_outbound_webhooks')
    op.drop_table('enterprise_outbound_webhooks')
    op.drop_index(op.f('ix_enterprise_group_role_mappings_organization_id'), table_name='enterprise_group_role_mappings')
    op.drop_index(op.f('ix_enterprise_group_role_mappings_id'), table_name='enterprise_group_role_mappings')
    op.drop_table('enterprise_group_role_mappings')
    op.drop_index(op.f('ix_enterprise_directory_sync_runs_organization_id'), table_name='enterprise_directory_sync_runs')
    op.drop_index(op.f('ix_enterprise_directory_sync_runs_id'), table_name='enterprise_directory_sync_runs')
    op.drop_table('enterprise_directory_sync_runs')
    op.drop_index(op.f('ix_enterprise_business_units_organization_id'), table_name='enterprise_business_units')
    op.drop_index(op.f('ix_enterprise_business_units_id'), table_name='enterprise_business_units')
    op.drop_table('enterprise_business_units')
    op.drop_index(op.f('ix_enterprise_access_policies_organization_id'), table_name='enterprise_access_policies')
    op.drop_index(op.f('ix_enterprise_access_policies_id'), table_name='enterprise_access_policies')
    op.drop_table('enterprise_access_policies')
    op.drop_index(op.f('ix_copilot_questionnaire_uploads_organization_id'), table_name='copilot_questionnaire_uploads')
    op.drop_index(op.f('ix_copilot_questionnaire_uploads_id'), table_name='copilot_questionnaire_uploads')
    op.drop_table('copilot_questionnaire_uploads')
    op.drop_index(op.f('ix_copilot_conversations_organization_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_mode'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_id'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    op.drop_index(op.f('ix_copilot_approved_security_answers_question_pattern'), table_name='copilot_approved_security_answers')
    op.drop_index(op.f('ix_copilot_approved_security_answers_organization_id'), table_name='copilot_approved_security_answers')
    op.drop_index(op.f('ix_copilot_approved_security_answers_id'), table_name='copilot_approved_security_answers')
    op.drop_table('copilot_approved_security_answers')
    op.drop_index(op.f('ix_partner_organizations_slug'), table_name='partner_organizations')
    op.drop_index(op.f('ix_partner_organizations_id'), table_name='partner_organizations')
    op.drop_table('partner_organizations')
    # ### end Alembic commands ###
