"""phase5_operations_observability_engine

Revision ID: d405af46acb7
Revises: 8eae332883a4
Create Date: 2026-10-01 21:42:17.028207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd405af46acb7'
down_revision: Union[str, Sequence[str], None] = '8eae332883a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_create_incident', sa.Boolean(), nullable=False),
    sa.Column('auto_rollback_release', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_environment_id'), 'alert_rules', ['environment_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('backup_observations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_point', sa.String(length=255), nullable=False),
    sa.Column('provider_backup_id', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_observations_environment_id'), 'backup_observations', ['environment_id'], unique=False)
    op.create_index(op.f('ix_backup_observations_id'), 'backup_observations', ['id'], unique=False)
    op.create_index(op.f('ix_backup_observations_organization_id'), 'backup_observations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_backup_observations_resource_id'), 'backup_observations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_backup_observations_status'), 'backup_observations', ['status'], unique=False)
    op.create_table('cost_alerts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_alerts_environment_id'), 'cost_alerts', ['environment_id'], unique=False)
    op.create_index(op.f('ix_cost_alerts_id'), 'cost_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_cost_alerts_organization_id'), 'cost_alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cost_alerts_status'), 'cost_alerts', ['status'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('forecast_monthly', sa.Float(), nullable=False),
    sa.Column('service_breakdown_json', sa.JSON(), nullable=False),
    sa.Column('daily_trend_json', sa.JSON(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_snapshots_captured_at'), 'cost_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_environment_id'), 'cost_snapshots', ['environment_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_id'), 'cost_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_organization_id'), 'cost_snapshots', ['organization_id'], unique=False)
    op.create_table('evidence_freshnesses',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('freshness_status', sa.String(length=50), nullable=False),
    sa.Column('resource_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_freshnesses_control_id'), 'evidence_freshnesses', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_freshnesses_framework'), 'evidence_freshnesses', ['framework'], unique=False)
    op.create_index(op.f('ix_evidence_freshnesses_freshness_status'), 'evidence_freshnesses', ['freshness_status'], unique=False)
    op.create_index(op.f('ix_evidence_freshnesses_id'), 'evidence_freshnesses', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_freshnesses_organization_id'), 'evidence_freshnesses', ['organization_id'], unique=False)
    op.create_table('health_snapshots',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('component_status_json', sa.JSON(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_snapshots_application_id'), 'health_snapshots', ['application_id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_captured_at'), 'health_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_health_snapshots_environment_id'), 'health_snapshots', ['environment_id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_id'), 'health_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_organization_id'), 'health_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_overall_status'), 'health_snapshots', ['overall_status'], unique=False)
    op.create_table('incidents',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('deployment_id', sa.String(length=36), nullable=True),
    sa.Column('alert_event_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('commander', sa.String(length=255), nullable=True),
    sa.Column('impact', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_actions', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('postmortem_markdown', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_alert_event_id'), 'incidents', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_incidents_application_id'), 'incidents', ['application_id'], unique=False)
    op.create_index(op.f('ix_incidents_deployment_id'), 'incidents', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_incidents_environment_id'), 'incidents', ['environment_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_release_id'), 'incidents', ['release_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_metric', sa.String(length=100), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('aggregation', sa.String(length=50), nullable=False),
    sa.Column('default_thresholds_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_metric_definitions_id'), 'metric_definitions', ['id'], unique=False)
    op.create_table('monitoring_configurations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_configurations_application_id'), 'monitoring_configurations', ['application_id'], unique=False)
    op.create_index(op.f('ix_monitoring_configurations_environment_id'), 'monitoring_configurations', ['environment_id'], unique=False)
    op.create_index(op.f('ix_monitoring_configurations_id'), 'monitoring_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_configurations_organization_id'), 'monitoring_configurations', ['organization_id'], unique=False)
    op.create_table('operational_changes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('infrastructure_plan_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_changes_application_id'), 'operational_changes', ['application_id'], unique=False)
    op.create_index(op.f('ix_operational_changes_environment_id'), 'operational_changes', ['environment_id'], unique=False)
    op.create_index(op.f('ix_operational_changes_id'), 'operational_changes', ['id'], unique=False)
    op.create_index(op.f('ix_operational_changes_occurred_at'), 'operational_changes', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_operational_changes_organization_id'), 'operational_changes', ['organization_id'], unique=False)
    op.create_table('security_signals',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_signals_environment_id'), 'security_signals', ['environment_id'], unique=False)
    op.create_index(op.f('ix_security_signals_id'), 'security_signals', ['id'], unique=False)
    op.create_index(op.f('ix_security_signals_organization_id'), 'security_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_signals_severity'), 'security_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_security_signals_status'), 'security_signals', ['status'], unique=False)
    op.create_table('service_level_objectives',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_level_objectives_environment_id'), 'service_level_objectives', ['environment_id'], unique=False)
    op.create_index(op.f('ix_service_level_objectives_id'), 'service_level_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_service_level_objectives_organization_id'), 'service_level_objectives', ['organization_id'], unique=False)
    op.create_table('uptime_checks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uptime_checks_environment_id'), 'uptime_checks', ['environment_id'], unique=False)
    op.create_index(op.f('ix_uptime_checks_id'), 'uptime_checks', ['id'], unique=False)
    op.create_index(op.f('ix_uptime_checks_organization_id'), 'uptime_checks', ['organization_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('alert_rule_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_environment_id'), 'alert_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_index(op.f('ix_alert_events_incident_id'), 'alert_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alert_events_organization_id'), 'alert_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alert_events_status'), 'alert_events', ['status'], unique=False)
    op.create_table('incident_timeline_events',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_events_id'), 'incident_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_incident_id'), 'incident_timeline_events', ['incident_id'], unique=False)
    op.create_table('restore_drills',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('backup_observation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rto_seconds', sa.Float(), nullable=True),
    sa.Column('data_validation_status', sa.String(length=50), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('target_temp_db_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_observation_id'], ['backup_observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restore_drills_backup_observation_id'), 'restore_drills', ['backup_observation_id'], unique=False)
    op.create_index(op.f('ix_restore_drills_environment_id'), 'restore_drills', ['environment_id'], unique=False)
    op.create_index(op.f('ix_restore_drills_id'), 'restore_drills', ['id'], unique=False)
    op.create_index(op.f('ix_restore_drills_organization_id'), 'restore_drills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_restore_drills_resource_id'), 'restore_drills', ['resource_id'], unique=False)
    op.create_index(op.f('ix_restore_drills_status'), 'restore_drills', ['status'], unique=False)
    op.create_table('slo_snapshots',
    sa.Column('slo_id', sa.String(length=36), nullable=False),
    sa.Column('actual_percentage', sa.Float(), nullable=False),
    sa.Column('error_budget_remaining', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slo_id'], ['service_level_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slo_snapshots_id'), 'slo_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_slo_snapshots_slo_id'), 'slo_snapshots', ['slo_id'], unique=False)
    op.create_table('uptime_results',
    sa.Column('uptime_check_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uptime_check_id'], ['uptime_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uptime_results_checked_at'), 'uptime_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_uptime_results_id'), 'uptime_results', ['id'], unique=False)
    op.create_index(op.f('ix_uptime_results_uptime_check_id'), 'uptime_results', ['uptime_check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uptime_results_uptime_check_id'), table_name='uptime_results')
    op.drop_index(op.f('ix_uptime_results_id'), table_name='uptime_results')
    op.drop_index(op.f('ix_uptime_results_checked_at'), table_name='uptime_results')
    op.drop_table('uptime_results')
    op.drop_index(op.f('ix_slo_snapshots_slo_id'), table_name='slo_snapshots')
    op.drop_index(op.f('ix_slo_snapshots_id'), table_name='slo_snapshots')
    op.drop_table('slo_snapshots')
    op.drop_index(op.f('ix_restore_drills_status'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_resource_id'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_organization_id'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_id'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_environment_id'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_backup_observation_id'), table_name='restore_drills')
    op.drop_table('restore_drills')
    op.drop_index(op.f('ix_incident_timeline_events_incident_id'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_id'), table_name='incident_timeline_events')
    op.drop_table('incident_timeline_events')
    op.drop_index(op.f('ix_alert_events_status'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_organization_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_incident_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_environment_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_uptime_checks_organization_id'), table_name='uptime_checks')
    op.drop_index(op.f('ix_uptime_checks_id'), table_name='uptime_checks')
    op.drop_index(op.f('ix_uptime_checks_environment_id'), table_name='uptime_checks')
    op.drop_table('uptime_checks')
    op.drop_index(op.f('ix_service_level_objectives_organization_id'), table_name='service_level_objectives')
    op.drop_index(op.f('ix_service_level_objectives_id'), table_name='service_level_objectives')
    op.drop_index(op.f('ix_service_level_objectives_environment_id'), table_name='service_level_objectives')
    op.drop_table('service_level_objectives')
    op.drop_index(op.f('ix_security_signals_status'), table_name='security_signals')
    op.drop_index(op.f('ix_security_signals_severity'), table_name='security_signals')
    op.drop_index(op.f('ix_security_signals_organization_id'), table_name='security_signals')
    op.drop_index(op.f('ix_security_signals_id'), table_name='security_signals')
    op.drop_index(op.f('ix_security_signals_environment_id'), table_name='security_signals')
    op.drop_table('security_signals')
    op.drop_index(op.f('ix_operational_changes_organization_id'), table_name='operational_changes')
    op.drop_index(op.f('ix_operational_changes_occurred_at'), table_name='operational_changes')
    op.drop_index(op.f('ix_operational_changes_id'), table_name='operational_changes')
    op.drop_index(op.f('ix_operational_changes_environment_id'), table_name='operational_changes')
    op.drop_index(op.f('ix_operational_changes_application_id'), table_name='operational_changes')
    op.drop_table('operational_changes')
    op.drop_index(op.f('ix_monitoring_configurations_organization_id'), table_name='monitoring_configurations')
    op.drop_index(op.f('ix_monitoring_configurations_id'), table_name='monitoring_configurations')
    op.drop_index(op.f('ix_monitoring_configurations_environment_id'), table_name='monitoring_configurations')
    op.drop_index(op.f('ix_monitoring_configurations_application_id'), table_name='monitoring_configurations')
    op.drop_table('monitoring_configurations')
    op.drop_index(op.f('ix_metric_definitions_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_release_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_environment_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_deployment_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_application_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_alert_event_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_health_snapshots_overall_status'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_organization_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_environment_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_captured_at'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_application_id'), table_name='health_snapshots')
    op.drop_table('health_snapshots')
    op.drop_index(op.f('ix_evidence_freshnesses_organization_id'), table_name='evidence_freshnesses')
    op.drop_index(op.f('ix_evidence_freshnesses_id'), table_name='evidence_freshnesses')
    op.drop_index(op.f('ix_evidence_freshnesses_freshness_status'), table_name='evidence_freshnesses')
    op.drop_index(op.f('ix_evidence_freshnesses_framework'), table_name='evidence_freshnesses')
    op.drop_index(op.f('ix_evidence_freshnesses_control_id'), table_name='evidence_freshnesses')
    op.drop_table('evidence_freshnesses')
    op.drop_index(op.f('ix_cost_snapshots_organization_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_environment_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_captured_at'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_cost_alerts_status'), table_name='cost_alerts')
    op.drop_index(op.f('ix_cost_alerts_organization_id'), table_name='cost_alerts')
    op.drop_index(op.f('ix_cost_alerts_id'), table_name='cost_alerts')
    op.drop_index(op.f('ix_cost_alerts_environment_id'), table_name='cost_alerts')
    op.drop_table('cost_alerts')
    op.drop_index(op.f('ix_backup_observations_status'), table_name='backup_observations')
    op.drop_index(op.f('ix_backup_observations_resource_id'), table_name='backup_observations')
    op.drop_index(op.f('ix_backup_observations_organization_id'), table_name='backup_observations')
    op.drop_index(op.f('ix_backup_observations_id'), table_name='backup_observations')
    op.drop_index(op.f('ix_backup_observations_environment_id'), table_name='backup_observations')
    op.drop_table('backup_observations')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_environment_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
